### ISSUE TITLE
v2.6.6 crash on android

### ISSUE THREAD

**Issue by SaeedDev94** [heiher/hev-socks5-tunnel#102]
v2.6.6 crash on android
```
CheckJNI: method to register "TProxyGetStats" not in the given class. This is slow, consider changing your RegisterNatives calls.
```

**Comment by heiher** [comment]
Thank you. Please add this line in your project:

https://github.com/heiher/sockstun/blob/2.0/app/src/main/java/hev/sockstun/TProxyService.java#L33
