### ISSUE TITLE
Ctrl+c

### ISSUE THREAD

**Issue by pronebird** [heiher/hev-socks5-tunnel#110]
Do you happen to capture signal handler in your lib (ctrl+c)? If so it would be great if that could be turned off because it steals the one that I set in my binary.

**Comment by heiher** [comment]
Thanks. SIGINT has been moved to main and is no longer included in API calls: https://github.com/heiher/hev-socks5-tunnel/commit/48e090a3e9255a3acfbbf8bf47f894a9fd0653c1
