### ISSUE TITLE
how to enable local dns

### ISSUE THREAD

**Issue by itsDantes** [heiher/hev-socks5-tunnel#112]
i want to enable local dns, what's the equal of [**this line**](https://github.com/2dust/v2rayNG/blob/09fc20794e73ebf4753caf213fba6d9c80315c12/V2rayNG/app/src/main/kotlin/com/v2ray/ang/service/V2RayVpnService.kt#L213) in this liberary ?

```
tunnel:
name: tun0,
mtu: 1500,

socks5:
address: 127.0.0.1,
port: 10808,
udp: udp,
```

does it enough?

**Comment by heiher** [comment]
it doesn't support local dns.
