### ISSUE TITLE
Compilation issues on Centos9

### ISSUE THREAD

**Issue by pronebird** [heiher/hev-socks5-tunnel#118]
Hi,

Just stumbled upon a mysterious error today when linking the static lib into rust project on Centos9, a lot of errors like this:

> /usr/bin/ld: [REDACTED]/third-party/lib/libhev-task-system.a(hev-memory-allocator-slice.o): relocation R_X86_64_32 against `.text' can not be used when making a PIE object; recompile with -fPIE
>
> /usr/bin/ld: [REDACTED]/third-party/lib/libhev-task-system.a(hev-task-aide.o): relocation R_X86_64_32 against `.bss' can not be used when making a PIE object; recompile with -fPIE

Naive approach of simply passing the flag doesn't help either:

```diff
diff --git a/Makefile b/Makefile
index d6d87cb..9e1e852 100644
--- a/Makefile
+++ b/Makefile
@@ -35,6 +35,8 @@ THIRDPARTS=$(THIRDPARTDIR)/yaml \
                   $(THIRDPARTDIR)/lwip \
                   $(THIRDPARTDIR)/hev-task-system
 
+$(STATIC_TARGET) : CCFLAGS+=-fPIC
+
 $(SHARED_TARGET) : CCFLAGS+=-fPIC
 $(SHARED_TARGET) : LDFLAGS+=-shared -pthread
```

The thing is that the static lib builds fine, but then Rust fails to link the compiled static libraries. Do you happen to know what could be the problem?

**Comment by pronebird** [comment]
Wanted to share that it seems that adding -fPIC in all makefiles works, see gist:

https://gist.github.com/pronebird/1b66745ac00773e88b16508522ff8d81

**Comment by heiher** [comment]
There is a rust binding for this project: https://github.com/heiher/tun2socks

**Comment by pronebird** [comment]
I know, but they don't compile on macOS.

**Comment by heiher** [comment]
> I know, but they don't compile on macOS as a dependency to my project.

Why link directly to `hev-socks5-tunnel` instead of `tun2socks` on macOS?

**Comment by heiher** [comment]
I think you can append `-fPIC` to CFLAGS:

```sh
make CFLAGS=-fPIC
```

**Comment by pronebird** [comment]
> Why link directly to hev-socks5-tunnel instead of tun2socks on macOS?

Back then, tun2socks 1.0.2 didn't compile on Mac, then I started working on adding the possibility to start the tunnel using string config instead of file. Today I pulled tun2socks 1.0.4 that you released yesterday and it seems to compile just fine across the board. So I am switching over to rust crate. Thanks.
