### ISSUE TITLE
support apple tv os ?

### ISSUE THREAD

**Issue by AddIcechan** [heiher/hev-socks5-tunnel#120]
I want to build the framework for apple tvOS, but I found it can't support.
will it support  to build tvOS framework?
thx.

**Comment by heiher** [comment]
I'm not

**Comment by AddIcechan** [comment]
> I'm not familiar with apple tv os. Could you create it based on the existing iOS framework?

I have tried  build framework for tvOS, but something wrong. some API cannot support in tvOS, just like 
```pid = fork();``` 
in`hev-exec.c`file. 
and some api wrong in lwip , etc
