### ISSUE TITLE
和shadowsocks-rust连接的时候，udp连接有问题，数据传输失败

### ISSUE THREAD

**Issue by Yewenyu** [heiher/hev-socks5-tunnel#121]
如题

`tunnel:
  mtu: 9000
  multi-queue: true

socks5:
  port: 7890
  address: ::1
  udp: 'udp'

misc:
  task-stack-size: 4096
  connect-timeout: 2000
  read-write-timeout: 2000
`

tun2socks log:

[log 3.log](https://github.com/heiher/hev-socks5-tunnel/files/14799090/log.3.log)

ssrust log:
[log.log](https://github.com/heiher/hev-socks5-tunnel/files/14799105/log.log)

**Comment by heiher** [comment]
根据我的实验，看上去是`shadowsocks-rust`的实现存在问题，当配置为`local_address`: `0.0.0.0`时，通过局域网其它主机访问udp是不通的。而当配置为`local_address`: `192.168.0.1`时，通过局域网段`192.168.0.0/24`的其它主机访问则没问题。

**Comment by Yewenyu** [comment]
192.168.0.1 是路由地址吧

**Comment by heiher** [comment]
> 192.168.0.1 是路由地址吧，还是本机在局域网的地址？

本机局域网地址

**Comment by Yewenyu** [comment]
> > 192.168.0.1 是路由地址吧，还是本机在局域网的地址？
> 
> 本机局域网地址

还是不行，不过确实shadowsocks-rust的问题，我用其他tun2socks也不行

**Comment by Yewenyu** [comment]
> > 192.168.0.1 是路由地址吧，还是本机在局域网的地址？
> 
> 本机局域网地址

请问 mode 那里填了 tcp是变成了 udp over tcp吗

**Comment by heiher** [comment]
> > > 192.168.0.1 是路由地址吧，还是本机在局域网的地址？
> > 
> > 
> > 本机局域网地址
> 
> 还是不行，不过确实shadowsocks-rust的问题，我用其他tun2socks也不行

我这测试可以，不过我这ss-rust只是socks5本地代理模式，没有上游。可能是你那的上游不支持吧

**Comment by heiher** [comment]
> > > 192.168.0.1 是路由地址吧，还是本机在局域网的地址？
> > 
> > 
> > 本机局域网地址
> 
> 请问 mode 那里填了 tcp是变成了 udp over tcp吗

对，但udp over tcp需要配合[hev-socks5-server](https://github.com/heiher/hev-socks5-server)的服务端。

**Comment by Yewenyu** [comment]
> > > > 192.168.0.1 是路由地址吧，还是本机在局域网的地址？
> > > 
> > > 
> > > 本机局域网地址
> > 
> > 
> > 请问 mode 那里填了 tcp是变成了 udp over tcp吗
> 
> 对，但udp over tcp需要配合[hev-socks5-server](https://github.com/heiher/hev-socks5-server)的服务端。

hev-socks5-server 可以用在移动端吗，应该怎么配置

**Comment by heiher** [comment]
> > > > > 192.168.0.1 是路由地址吧，还是本机在局域网的地址？
> > > > 
> > > > 
> > > > 本机局域网地址
> > > 
> > > 
> > > 请问 mode 那里填了 tcp是变成了 udp over tcp吗
> > 
> > 
> > 对，但udp over tcp需要配合[hev-socks5-server](https://github.com/heiher/hev-socks5-server)的服务端。
> 
> hev-socks5-server 可以用在移动端吗，应该怎么配置

可以跑在移动端，不过这是什么场景？

**Comment by Yewenyu** [comment]
> > > > > > 192.168.0.1 是路由地址吧，还是本机在局域网的地址？
> 
> > > > > 
> 
> > > > > 
> 
> > > > > 本机局域网地址
> 
> > > > 
> 
> > > > 
> 
> > > > 请问 mode 那里填了 tcp是变成了 udp over tcp吗
> 
> > > 
> 
> > > 
> 
> > > 对，但udp over tcp需要配合[hev-socks5-server](https://github.com/heiher/hev-socks5-server)的服务端。
> 
> > 
> 
> > hev-socks5-server 可以用在移动端吗，应该怎么配置
> 
> 
> 
> 可以跑在移动端，不过这是什么场景？

我想试试能不能用udp over tcp连上shadowsocks-rust

**Comment by heiher** [comment]
> > > > > > > 192.168.0.1 是路由地址吧，还是本机在局域网的地址？
> > 
> > 
> > > > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > > > > 本机局域网地址
> > 
> > 
> > > > >
> > 
> > 
> > > > >
> > 
> > 
> > > > > 请问 mode 那里填了 tcp是变成了 udp over tcp吗
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > 对，但udp over tcp需要配合[hev-socks5-server](https://github.com/heiher/hev-socks5-server)的服务端。
> > 
> > 
> > > 
> > 
> > 
> > > hev-socks5-server 可以用在移动端吗，应该怎么配置
> > 
> > 
> > 可以跑在移动端，不过这是什么场景？
> 
> 我想试试能不能用udp over tcp连上shadowsocks-rust

可以用ss协议作为hev-socks5-tunnel和hev-socks5-server的桥梁，直接在hev-socks5-tunnel和ss-rust之间使用udp-over-tcp不行。
