### ISSUE TITLE
ssh tunnel +  hev-socks5-tunnel

### ISSUE THREAD

**Issue by tormentous** [heiher/hev-socks5-tunnel#127]
ssh tunnel dynamic port forwarding connected to 127.0.0.1:1080 but does not work, I use android build

2024-05-03 13:18:46.332 11679-11724 MyLog  hev.sockstun  E  [2024-05-03 13:18:46] [E] 0x743a676850 socks5 session handshake
2024-05-03 13:18:46.485 11679-11718 MyLog hev.sockstun   E  [2024-05-03 13:18:46] [E] 0x743a676850 socks5 client res.rep 7

**Comment by heiher** [comment]
Does the socks5 server support udp?

**Comment by tormentous** [comment]
Yes. In here I can make an account

https://sshocean.com/ssh

**Comment by heiher** [comment]
ssh port forwarding only maps TCP port 1080, which does not make UDP available unless udp-relay-over-tcp is used, which requires hev-socks5-server.

**Comment by tormentous** [comment]
> ssh port forwarding only maps TCP port 1080, which does not make UDP available unless udp-relay-over-tcp is used, which requires hev-socks5-server.

if I enable udp-relay-over-tcp, log shows the same and now "Unsupport Command"
