### ISSUE TITLE
Udp tcp over socks

### ISSUE THREAD

**Issue by armantc** [heiher/hev-socks5-tunnel#13]
In my vps server , i install softether vpn server that use tap devie with 192.168.24.0/21 subnet . Traffic of this devoce go throuh gateway if eth0 ip.
With some iptables trick can forward tcp to local go simple tunnel and use tls tunnel to coonect to socks server on another vps . Beacuse of many restriction on internet in our country . But mg problem is with udp traffic . How i can forward udp this way . I was test tun2soxks but i cant got it working beacuse when change metrics with way say in exampl , i lost connection to device .  Can i do it with hev ?

**Comment by heiher** [comment]
Certainly. If you want to proxy UDP, you should use [hev-socks5-server](https://github.com/heiher/hev-socks5-server) on server side vps. BTW, the traffic in direct access is not encrypted or obfuscated.

It should be noted that if you use the global default route, you need to bypass the socks5 server address to avoid it going through the virtual tunnel:

```bash
ip route add SOCKS5-SERVER-IP dev INTERNET-IFACE metric 10

ip route add default dev tun0 metric 20
ip -6 route add default dev tun0 metric 20
```

**Comment by armantc** [comment]
> Certainly. If you want to proxy UDP, you should use [hev-socks5-server](https://github.com/heiher/hev-socks5-server) on server side vps. BTW, the traffic in direct access is not encrypted or obfuscated.
> 
> It should be noted that if you use the global default route, you need to bypass the socks5 server address to avoid it going through the virtual tunnel:
> 
> ```shell
> ip route add SOCKS5-SERVER-IP dev INTERNET-IFACE metric 10
> 
> ip route add default dev tun0 metric 20
> ip -6 route add default dev tun0 metric 20
> ```

tnx for quick answer , for tap device to use tun0 as gateway what rule must add ?
i want be like this :
tap_se  ==>  tun0  ==>  eth0

tap_se has subnet 192.168.0.21/24 with netmask 255.255.248.0 and brodcast 192.168.31.255 and ip of router 192.168.24.0

**Comment by heiher** [comment]
I need more info about your network topology.

**Comment by heiher** [comment]
Run hev-socks5-server directly on vpsserver, and hev-socks5-tunnel on another without softether, if encryption is not required. (or use a tcp stream wrapper to encrypt socks5 traffic between server and client. e.g. ssh port forwarding?)

vps server:

```bash
hev-socks5-server conf.yml # default config
```

another host:

```bash
hev-socks5-tunnel conf.yml # socks5 sever point to vpsservet

ip route add vpsserver dev eth0
ip route default dev tun0
```

**Comment by never-afk** [comment]
> 当然。如果你想代理 UDP，你应该在服务器端 vps 上使用[hev-socks5-server](https://github.com/heiher/hev-socks5-server)。顺便说一句，直接访问中的流量未加密或混淆。
> 
> 需要注意的是，如果使用全局默认路由，需要绕过socks5服务器地址，避免走虚拟隧道：
> 
> ```shell
> ip route add SOCKS5-SERVER-IP dev INTERNET-IFACE metric 10
> 
> ip route add default dev tun0 metric 20
> ip -6 route add default dev tun0 metric 20
> ```

Is there a plan to develop the original udp proxy?  If not,lay4 VPN like v2ray xray is not easy to use hev-socks5-tunnel

**Comment by heiher** [comment]
> Is there a plan to develop the original udp proxy? If not,lay4 VPN like v2ray xray is not easy to use hev-socks5-tunnel

I'm currently too occupied to add this feature.

**Comment by heiher** [comment]
> Is there a plan to develop the original udp proxy? If not,lay4 VPN like v2ray xray is not easy to use hev-socks5-tunnel

Adding UDP associate support is done: https://github.com/heiher/hev-socks5-tunnel/commit/f5311b06fcce4d5255d1feea52c3ba3a7de756c9

```yaml
socks5:
  # Socks5 UDP relay mode (tcp|udp)
  udp: 'udp'
```

Please let me know if you have any other questions.

**Comment by A5DkjGQUZx** [comment]
> > Is there a plan to develop the original udp proxy? If not,lay4 VPN like v2ray xray is not easy to use hev-socks5-tunnel
> 
> Adding UDP associate support is done: [f5311b0](https://github.com/heiher/hev-socks5-tunnel/commit/f5311b06fcce4d5255d1feea52c3ba3a7de756c9)
> 
> ```yaml
> socks5:
>   # Socks5 UDP relay mode (tcp|udp)
>   udp: 'udp'
> ```
> 
> Please let me know if you have any other questions.

Have you tested this in practice? I am now almost 100% confident that that the Hev does not pass DNS UDP traffic. Compiled code from the last commit.

When I use `curl -sSx socks5h://localhost:1080 https://checkip.amazonaws.com`  I get the DNS query on my socks server and the proxy works fine.
When I use  `curl -sS --interface tun0 --dns-interface tun0 --dns-ipv4-addr 9.9.9.9  https://checkip.amazonaws.com`, the DNS UDP is leaked from tun0 to the eth0 interface.
Not only is this a problem, but it also can be dangerous from a privacy point of view...

**Comment by A5DkjGQUZx** [comment]
```
#!/bin/sh
/usr/bin/hev-socks5-tunnel /usr/bin/hevsocksconfig.yaml \
& ifconfig eth0:0 192.168.70.2 netmask 255.255.255.0

ip rule add pref 300 from 192.168.70.0/24 table tun2socks

iptables -A FORWARD -i eth0:0 -s 192.168.70.0/24 -j ACCEPT
iptables -A FORWARD -i tun0 -d 192.168.70.0/24 -j ACCEPT
iptables -t nat -A POSTROUTING -s 192.168.70.0/24 -o tun0 -j MASQUERADE

ip route flush table tun2socks
ip route show table main | grep -Ev ^default | while read ROUTE ; do ip route add table tun2socks $ROUTE; done
ip route add default via 10.0.0.1 dev tun0 table tun2socks

ip route flush cache

/usr/local/bin/xray run /usr/local/bin/config.json

```

Someday someone might find this script useful for NATing a local network traffic to Hev tun0 and then pass it by the tun2socks to a Xray or V2ray or V2fly client connection over socks...
**(PAY ATTENTION TO THE "pref 300" AS IT IS CRITICALLY IMPORTANT)**

I had limited Kernel Modules and was not able to utilize Tmark Iptables modules. So had to use a tun2socks adapter and do an old fashion typical nat.

Works fine with latest Hev build. 

```
speedtest -I tun0

   Speedtest by Ookla

      Server: KPN - Amsterdam (id: 26996)
Idle Latency:    96.52 ms   (jitter: 1.17ms, low: 95.34ms, high: 97.32ms)
    Download:   452.90 Mbps (data used: 584.0 MB)                                                   
                290.17 ms   (jitter: 69.22ms, low: 95.39ms, high: 458.78ms)
      Upload:   378.08 Mbps (data used: 535.0 MB)                                                   
                121.87 ms   (jitter: 8.42ms, low: 102.21ms, high: 162.63ms)
 Packet Loss:     0.0%
```
