### ISSUE TITLE
best settings for less latency

### ISSUE THREAD

**Issue by itsDantes** [heiher/hev-socks5-tunnel#133]
Thank you for this great project. I use this project in my **program**. The application of my program is to **reduce the delay (LAG)** so that they can have a better experience in **online games** in **Android**. How can I apply settings in the best possible way? I mean settings like mtu, task-stack-size, and etc...

**Comment by heiher** [comment]
Can you provide a baseline for the current code? And what is the expected optimal latency?

**Comment by itsDantes** [comment]
@heiher . its just a simple VPN service for android. i just want to know if the **mtu size** or **multi-queue** or **misc settings** can effect on latency ?

**Comment by heiher** [comment]
> @heiher . its just a simple VPN service for android. i just want to know if the **mtu size** or **multi-queue** or **misc settings** can effect on latency ?

No.

**Comment by itsDantes** [comment]
@heiher well. thanks.
