### ISSUE TITLE
在 macos 上有crash

### ISSUE THREAD

**Issue by Yewenyu** [heiher/hev-socks5-tunnel#134]
![412675838](https://github.com/heiher/hev-socks5-tunnel/assets/23135563/f5b3a5e0-6446-43d5-9f7f-55a0c9498cf5)
![2794230798](https://github.com/heiher/hev-socks5-tunnel/assets/23135563/025b6aad-cc45-4d9e-a2bd-e2fc6fe5a674)
![200838437](https://github.com/heiher/hev-socks5-tunnel/assets/23135563/ff620ba9-d4d2-43ab-a3ba-90836b0c28e4)
![1315098732](https://github.com/heiher/hev-socks5-tunnel/assets/23135563/eaec962f-15a2-4012-9634-13ef740d139f)
![3682539047](https://github.com/heiher/hev-socks5-tunnel/assets/23135563/e79fa8a2-732f-4e59-9a9e-1201b413527c)
![1177464268](https://github.com/heiher/hev-socks5-tunnel/assets/23135563/60bf4396-41fe-43aa-9b3b-8366a9fa41fb)
![1496813081](https://github.com/heiher/hev-socks5-tunnel/assets/23135563/b886616d-ce5f-4740-94cf-f5eece6ad3c6)

**Comment by Yewenyu** [comment]
> Check the task-stack-size (>= 81920): https://github.com/heiher/hev-socks5-tunnel/blob/master/conf/main.yml#L37

`tunnel:
  mtu: 9000
  multi-queue: true

socks5:
  port: 7890
  address: ::1
  udp: 'udp'

misc:
  task-stack-size: 4096
  connect-timeout: 2000
  read-write-timeout: 2000
`
你的意思是必须大于81920吗

**Comment by heiher** [comment]
> 你的意思是必须大于81920吗

对的。为了整体上更节省内存，现在Ring Buffer在栈上分配。

（后面考虑在配置模块中增加最低阈值限制，以避免这类配置导致的问题。

**Comment by heiher** [comment]
https://github.com/heiher/hev-socks5-tunnel/commit/9f2b55c8a95f7a5978aad533d137d0a5ca5bdb86

**Comment by heiher** [comment]
试试再调高`task-stack-size`测测，如果还是有不行，就是其它未知问题了。最好能定位一下是哪个修改引起的，提供更详细的错误上下文信息。

**Comment by sholiverlee** [comment]
我也碰到了这个问题

**Comment by Yewenyu** [comment]
> 试试再调高`task-stack-size`测测，如果还是有不行，就是其它未知问题了。最好能定位一下是哪个修改引起的，提供更详细的错误上下文信息。



> 我也碰到了这个问题

task-stack-size 调到 102400就可以了

**Comment by heiher** [comment]
正常来说`task-stack-size: 81920`应该足够了，这已经是包含了一定的冗余了。如果是栈溢出导致的问题，也可以试试 `make CFLAGS="-fno-stack-protector"` 编译，以防止是某些版本的编译器默认开启了比较激进的栈保护。

**Comment by heiher** [comment]
> > 试试再调高`task-stack-size`测测，如果还是有不行，就是其它未知问题了。最好能定位一下是哪个修改引起的，提供更详细的错误上下文信息。
> 
> > 我也碰到了这个问题
> 
> task-stack-size 调到 102400就可以了

默认的`task-stack-size`还需要调大吗？

**Comment by sholiverlee** [comment]
不需要调大了，已经可以了。非常感谢支持！

**Comment by heiher** [comment]
> 不需要调大了，已经可以了。非常感谢支持！

那就好，谢谢~

**Comment by Yewenyu** [comment]
> > > 试试再调高`task-stack-size`测测，如果还是有不行，就是其它未知问题了。最好能定位一下是哪个修改引起的，提供更详细的错误上下文信息。
> > 
> > 
> > > 我也碰到了这个问题
> > 
> > 
> > task-stack-size 调到 102400就可以了
> 
> 默认的`task-stack-size`还需要调大吗？

我在mac arm架构的不需要，在x86上就需要调大

**Comment by Yewenyu** [comment]
> @Yewenyu 感谢反馈，能否提供一下具体的复现的步骤，比如使用什么发行版和什么工具链版本？

使用了clash的trojan，开启了websocket
