### ISSUE TITLE
Illegal instruction on mips32el

### ISSUE THREAD

**Issue by VladimirChalanov** [heiher/hev-socks5-tunnel#136]
Versions 2.6.8 and 2.6.9 don't work. When launched without parameters, the program displays the version. If I specify the config.yml then it will display "Illegal instruction" error.

Version 2.6.7 works fine.

I use tunnel on openwrt router (Linux 5.10.201 mips GNU/Linux).
<details><summary>cpuinfo</summary>
<p>

system type		: MediaTek MT7628AN ver:1 eco:2
machine			: ZyXEL Keenetic Extra II
processor		: 0
cpu model		: MIPS 24KEc V5.5
BogoMIPS		: 385.84
wait instruction	: yes
microsecond timers	: yes
tlb_entries		: 32
extra interrupt vector	: yes
hardware watchpoint	: yes, count: 4, address/irw mask: [0x0ffc, 0x0ffc, 0x0ffb, 0x0ffb]
isa			: mips1 mips2 mips32r1 mips32r2
ASEs implemented	: mips16 dsp
Options implemented	: tlb 4kex 4k_cache prefetch mcheck ejtag llsc pindexed_dcache userlocal vint perf_cntr_intr_bit perf
shadow register sets	: 1
kscratch registers	: 0
package			: 0
core			: 0
VCED exceptions		: not available
VCEI exceptions		: not available

</p>
</details>

**Comment by heiher** [comment]
could you paste your config?

**Comment by heiher** [comment]
Thanks. I figured it out. It will be fixed in next version.

**Comment by heiher** [comment]
https://github.com/heiher/hev-socks5-tunnel/releases/download/2.7.0/hev-socks5-tunnel-linux-mips32elsf
