### ISSUE TITLE
line 3: syntax error: unexpected "|" (expecting ")")

### ISSUE THREAD

**Issue by GektorUA** [heiher/hev-socks5-tunnel#14]
Hi, i am trying to test 2.4.3 version and get:
/usr/bin/hev-socks5-tunnel-linux-x86_64: line 3: syntax error: unexpected "|" (expecting ")")

**Comment by heiher** [comment]
try to download pre-compiled executable in browser and run with default config file at `conf/main.yml`.

**Comment by heiher** [comment]
I need more details to reproduce about openwrt version/cpu arch, socks5 server and socks5-tunnel commit id.

**Comment by heiher** [comment]
Thanks for your info.

First of all, I suggest you try to use hev-socks5-tunnel (head commit of master branch) and enable udp in udp in config file to avoid this error:

> [E] 0xc3a910 socks5 client res.rep 7

```yaml
socks5:
  udp: udp
```

And then, This is an interesting question! I probably can't figure out why until I reproduce it. I have tested hev-socks5-tunnel (master) on x86-64 using xray (v1.7.5) as server and everything looks well:

xray config:

```json
{
  "log": {
    "loglevel": "warning"
  },
  "inbounds": [
    {
      "tag": "socks-in",
      "protocol": "socks",
      "listen": "0.0.0.0",
      "port": 1080,
      "settings": {
        "auth": "noauth",
        "udp": true,
        "ip:": "192.168.0.8"
      }
    }
  ],
  "outbounds": [
    {
      "tag": "direct",
      "protocol": "freedom"
    }
  ]
}
```

```
Client <-------- 1Gbps ----------> Server
```

* Upload

```bash
iperf3 -c 192.168.0.8
```

```
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-10.00  sec  1.08 GBytes   926 Mbits/sec    0             sender
[  5]   0.00-10.04  sec  1.08 GBytes   920 Mbits/sec                  receiver
```

* Download

```bash
iperf3 -c 192.168.0.8 -R
```

```
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-10.04  sec  1.09 GBytes   934 Mbits/sec    0             sender
[  5]   0.00-10.00  sec  1.08 GBytes   928 Mbits/sec                  receiver
```

At last, The Android VPN client based on hev-socks5-tunnel(master) looks well too with xray v1.7.5 over WiFi connection:

https://github.com/heiher/sockstun

**Comment by heiher** [comment]
Thanks for help debugging on your devices, Please let me know if you have any other questions.
