### ISSUE TITLE
x86_64 环境莫名 crash

### ISSUE THREAD

**Issue by yiguous** [heiher/hev-socks5-tunnel#140]
<img width="1043" alt="截屏2024-06-25 21 40 33" src="https://github.com/heiher/hev-socks5-tunnel/assets/147401898/193b84f8-efd4-4794-a008-6c32e094080b">
<img width="1165" alt="截屏2024-06-25 21 41 13" src="https://github.com/heiher/hev-socks5-tunnel/assets/147401898/a6b08e5a-70fc-48df-9f73-030c8278afc3">
<img width="498" alt="截屏2024-06-25 21 41 33" src="https://github.com/heiher/hev-socks5-tunnel/assets/147401898/a78677bf-6c44-4a69-bf75-0dc931754578">

测试机型: Macmini 2018
测试版本：2.7.0

目前已验证该问题在 2.6.9 引入，回退至 2.6.8 之后正常。

**Comment by heiher** [comment]
看看是不是这个问题： https://github.com/heiher/hev-socks5-tunnel/issues/134#issuecomment-2128438910

如果调大`task-stack-size`到`102400`比较保险会将其设置为默认值。

**Comment by yiguous** [comment]
确实是同一个问题。感谢🙏。

**Comment by heiher** [comment]
@yiguous 你的环境`task-stack-size`最低到多少是稳定的？

**Comment by yiguous** [comment]
这两天我详细测试下。

**Comment by yiguous** [comment]
真想如此之近，让人泪流满面。😂


默认值：81920 = 80k
无法启动

81920 + 1 = 81921 = 80k + 1B = 80k1B
speedtest.net download 235 Mbps, 稳定存活

81920 + 2 = 81922 = 80k + 2B = 80k2B
speedtest.net download 204 Mbps, 稳定存活

81920 + 4 = 81924 = 80k + 4B = 80k4B
speedtest.net download 126 Mbps, 稳定存活

81920 + 8 = 81928 = 80k + 8B = 80k8B
speedtest.net download 119 Mbps, 稳定存活

81920 + 16 = 81936 = 80k + 16B = 80k16B
speedtest.net download 165 Mbps, 稳定存活

81920 + 32 = 81952 = 80k + 32B = 80k32B
speedtest.net download 243 Mbps, 稳定存活

81920 + 64 = 81984 = 80k + 64B = 80k64B
speedtest.net download 233 Mbps, 稳定存活

81920 + 128 = 82048 = 80k + 128B = 80k128B
speedtest.net download 219 Mbps, 稳定存活

81920 + 256 = 82176 = 80k + 256B = 80k256B
speedtest.net download 253 Mbps, 稳定存活

81920 + 512 = 82432 = 80k + 512B = 80k512B
speedtest.net download 267 Mbps, 稳定存活

81920 + 1024 = 82944 = 80k + 1k = 81k
speedtest.net download 264 Mbps, 稳定存活

81920 + 1024*2 = 83968 = 80k + 2k = 82k
speedtest.net download 175 Mbps, 稳定存活

81920 + 1024*3 = 84992 = 80k + 3k = 83k
speedtest.net download 273 Mbps, 稳定存活

81920 + 1024*4 = 86016 = 80k + 4k = 84k
speedtest.net download 288 Mbps, 稳定存活

81920 + 1024*5 = 87040 = 80k + 5k = 85k
speedtest.net download 244 Mbps, 稳定存活

81920 + 1024*10 = 92160 = 80k + 10k = 90k
speedtest.net download 196 Mbps, 稳定存活

81920 + 1024*20 = 102400 = 80k + 20k = 100k
speedtest.net download 228 Mbps, 稳定存活

**Comment by yiguous** [comment]
测试环境
OS：macOS 14.5
Hardware: Mac mini 2018
Core: Intel i3
RAM: 16G

**Comment by heiher** [comment]
@yiguous 哈哈，谢谢。我给默认值再增加4K。
