### ISSUE TITLE
psiphon in warp

### ISSUE THREAD

**Issue by itsDantes** [heiher/hev-socks5-tunnel#154]
hey @heiher.

i use your library with [oblivion](https://github.com/bepass-org/oblivion).

the oblivion app using cloudflare warp or wireguard protocols,  so users can connect to free Internet. 

it has its own proxy library, that called [tun2socks.go](https://github.com/bepass-org/oblivion/blob/main/tun2socks/tun2socks.go).  as you see from [this line](https://github.com/bepass-org/oblivion/blob/08cf04ae9a8de4bb81971f84fde5f723092830eb/app/src/main/java/org/bepass/oblivion/service/OblivionVpnService.java#L598) it pass device tun to the tun2socks.go app and it makes proxy for it. 

i just removed [this line](https://github.com/bepass-org/oblivion/blob/08cf04ae9a8de4bb81971f84fde5f723092830eb/tun2socks/tun2socks.go#L141) and its below codes from it and made it free without passing user tun. 

now the problem is, everything is okay in warp OR warp in warp mode. 

but when i want to use Psiphon in Warp,  the tunnel is not working and it seem your libary cant proxy it. 

this problem is related to your project? why it can proxy warp or warp in warp, but in Psiphon in Warp it not works at all? 

but its own tun2socks.go library can proxy all of 3 modes without any problem. 

if you check tun2socks.go file, you will see it handel all of 3 modes with its own small codes. it getting needed variables from android app and pass it to the go app. like what your app do, but in C language. 
both of them getting users device tun connection for their proxy and needed things. but i really don't know why when i use Psiphon in Warp mode, the user VPN tunnel not proxies so nothing works until i stop VPN.

**Comment by itsDantes** [comment]
@heiher  what is this errors mean ?

![share](https://github.com/user-attachments/assets/7bb3e099-241e-418d-aee8-ae68a394c1e8)

**Comment by heiher** [comment]
https://github.com/heiher/hev-socks5-core/blob/master/src/hev-socks5-proto.h#L58
