### ISSUE TITLE
iOS无法连接。

### ISSUE THREAD

**Issue by EricsXcode** [heiher/hev-socks5-tunnel#157]
博主，我使用该库出现iOS无法连接到xray的问题。xray已启动端口的监听，但tun2一直在链接中。我使用本机的局域网ip则可以连接成功，使用127.0.0.1则无法连接。
xray日志：
2024/09/04 09:25:33 [Debug] app/proxyman/inbound: creating stream worker on 127.0.0.1:1085
2024/09/04 09:25:33 [Debug] app/proxyman/inbound: creating stream worker on 127.0.0.1:1082
2024/09/04 09:25:33 [Info] transport/internet/tcp: listening TCP on 127.0.0.1:1085
2024/09/04 09:25:33 [Info] transport/internet/udp: listening UDP on 127.0.0.1:1085
2024/09/04 09:25:33 [Info] transport/internet/tcp: listening TCP on 127.0.0.1:1082
tun2日志：一直循环下面的过程
[2024-09-04 17:26:58] [D] 0x107509a20 socks5 session run
[2024-09-04 17:26:58] [D] 0x107509a20 socks5 client connect [127.0.0.1]:1085
[2024-09-04 17:26:58] [D] 0x107509a20 socks5 client connect server
[2024-09-04 17:26:58] [D] 0x107509a20 socks5 session udp bind
[2024-09-04 17:26:58] [E] 0x107509a20 socks5 client connect
[2024-09-04 17:26:58] [E] 0x107509a20 socks5 client connect
[2024-09-04 17:26:58] [E] 0x107509a20 socks5 session connect
[2024-09-04 17:26:58] [D] 0x107509a20 socks5 session udp destruct
[2024-09-04 17:26:58] [D] 0x107509a20 socks5 client udp destruct
[2024-09-04 17:26:58] [D] 0x107509a20 socks5 client destruct
[2024-09-04 17:26:58] [D] 0x107509a20 socks5 destruct
xray路由：
     @{
           @"listen" : @"127.0.0.1",
           @"protocol": @"socks",
           @"settings" : @{
               @"auth": @"noauth",//@"password",
               @"udp":@(YES),
               @"ip":@"127.0.0.1",
           },
           @"tag" : @"socks-in",
           @"port" : @(1085)
       };
隧道配置：
 NEPacketTunnelNetworkSettings *networkSettings = [[NEPacketTunnelNetworkSettings alloc] initWithTunnelRemoteAddress:@"254.1.1.1"];:
    NSMutableSet *dns = [NSMutableSet setWithArray:[NAFutureManager sharedManager].DNS];
    
    [_allDnsServer addObjectsFromArray:dns.allObjects];
    networkSettings.DNSSettings = [[NEDNSSettings alloc] initWithServers:_allDnsServer];
    networkSettings.MTU = @(8500);
    
    // 此处其实是创建一个虚拟 IP 地址，需要自行创建路由
    NEIPv4Settings *ipv4Settings = [[NEIPv4Settings alloc] initWithAddresses:@[@"198.18.0.1"] subnetMasks:@[@"255.255.255.0"]];
    networkSettings.IPv4Settings = ipv4Settings;

**Comment by heiher** [comment]
不清楚怎么回事，也没环境分析，检查一下路由？记得有人说过类似的问题，用`:1`也能访问。

**Comment by EricsXcode** [comment]
> 不清楚怎么回事，也没环境分析，检查一下路由？记得有人说过类似的问题，用`:1`也能访问。

我使用ipv6的地址创建监听，然后使用::1链接就没问题。使用ipv4 就链接不上。

**Comment by yiguous** [comment]
确实存在这个问题，Apple 专属。其他平台监听 **127.0.0.1** 完全没问题（已验证 Android, Linux）。
但是我觉得没有解决的必要，监听 **::1** 完全可以达到同样的效果。

**Comment by heiher** [comment]
建议通过 `::1` 访问解决。

**Comment by dhp5** [comment]
> > 不清楚怎么回事，也没环境分析，检查一下路由？记得有人说过类似的问题，用`:1`也能访问。
> 
> 我使用ipv6的地址创建监听，然后使用::1链接就没问题。使用ipv4 就链接不上。

你好，请问这个问题，你解决了么？我添加ipv6 + ::1也不能解决，还是报这个错误。在ipone8 ios16的系统上。但是同样的代码在ipone14 ios17上是完全可以用的

**Comment by ccwater666** [comment]
> > > 不清楚怎么回事，也没环境分析，检查一下路由？记得有人说过类似的问题，用`:1`也能访问。
> > 
> > 
> > 我使用ipv6的地址创建监听，然后使用::1链接就没问题。使用ipv4 就链接不上。
> 
> 你好，请问这个问题，你解决了么？我添加ipv6 + ::1也不能解决，还是报这个错误。在ipone8 ios16的系统上。但是同样的代码在ipone14 ios17上是完全可以用的

xray上不要listen 127.0.0.1， 用0.0.0.0可以解决， ios15和ios16上， 但是 ios17和ios18都可以直接使用127.0.0.1.就非常神奇。
