### ISSUE TITLE
Flutter Android ANR

### ISSUE THREAD

**Issue by LondonX** [heiher/hev-socks5-tunnel#162]
Hi, you made a good job on this repo.

I tried to make it run in Flutter Android App, when I call `TProxyStopService()` which calls `native_stop_service` in hev-jni.c, it makes Flutter App unable to response any input, that makes ANR alert.

When ANR happens, App can still rendering, updating screen, make other background progress.

It issue may be caused by some code in `pthread_mutex_lock`, as I comment all code in `native_stop_service` except `hev_socks5_tunnel_quit ();`, it seems works fine, but does it have some side-effect?

**Comment by LondonX** [comment]
Woo, I may solved this problem by my self, but I don't understand exactly how lol.

The ANR may caused by stopping a NOT-connected-TUN.
I modify the codes about `VpnService.Builder` along with `sockstun` repo to make successful establishing the connect of tun, and after established, `TProxyStopService()` works without ANR, weird.

> as I comment all code in native_stop_service except hev_socks5_tunnel_quit ();
This operation seem like causing a issue that makes tun not usable (RX/TX always 0 in ifconfig).

**Comment by smj1234** [comment]
how you even get the .so files out?  i stuck with 1000 erors  :)))
