### ISSUE TITLE
Release binaries for arm32 with softfloat

### ISSUE THREAD

**Issue by ameir** [heiher/hev-socks5-tunnel#164]
I would like to run this on a Linksys EA6900 router, which uses the armv7l processor. This is a softfloat processor. I have tried your existing binaries, but unfortunately, none of them work beyond the `--version` flag.

Would it be possible to add support for this processor?

```
# cat /proc/cpuinfo
Processor	: ARMv7 Processor rev 0 (v7l)
processor	: 0
BogoMIPS	: 1599.07

processor	: 1
BogoMIPS	: 1595.80

Features	: swp half thumb fastmult edsp
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x3
CPU part	: 0xc09
CPU revision	: 0

Hardware	: Northstar Prototype
Revision	: 0000
Serial		: 0000000000000000
```

**Comment by heiher** [comment]
The ARM32 soft-float in musl-cross (version 20240903 and earlier) is broken. I'll update the toolchain to fix it.

**Comment by heiher** [comment]
Could you try it on your device? Thanks.

https://github.com/heiher/hev-socks5-tunnel/releases/tag/2.7.4-next

**Comment by ameir** [comment]
I didn't run it completely (I need to create a config file and such now), but it's not segfaulting for me now, which is great. Thank you for the prompt fix!

**Comment by heiher** [comment]
Thank you.
