### ISSUE TITLE
无法使用SSH

### ISSUE THREAD

**Issue by shandftk** [heiher/hev-socks5-tunnel#170]
因为我选择了全局模式流量，添加了default dev tun0 scope link metric 20，删除了default dev eth0 scope link，目前出站工作正常，但是无法ssh到服务器了，请问有什么办法吗？我尝试了nftables打mark，配合ip rule 和建立了ip route table 表，强制使用eth0，但是不起作用，抓包看到流量依旧流入tun0网卡，也尝试prerouting捕捉，依然不起作用。
这是我的nftables配置：
table inet filter {
    chain prerouting {
        type filter hook prerouting priority -300; policy accept;
        ip protocol tcp tcp dport 22 meta mark set 0x1
    }

    chain input {
        type filter hook input priority 0; policy accept;
        tcp dport 22 meta mark set 0x1
    }

    chain output {
        type filter hook output priority 0; policy accept;
        tcp sport 22 meta mark set 0x1
    }
}

**Comment by heiher** [comment]
这个场景需要配置“源进源出”的策略路由，以避免物理网卡网段的报文路由至虚拟网卡。比如物理网卡的IP地址段是`192.168.1.0/24`，则配置：

```bash
ip rule add from 192.168.1.0/24 lookup main pref 10  # pref 值低于虚拟网卡的
```

**Comment by shandftk** [comment]
非常感谢，已解决
