### ISSUE TITLE
Reuse of udp relay

### ISSUE THREAD

**Issue by 5andr0** [heiher/hev-socks5-tunnel#175]
Thanks for making this open source!

Is this requesting a new socks5 udp relay server every time there's a different destination addr or source port?
It would be nice if the udp relay is only requested once and then used for all different destinations since you can redirect to the right client or destination by the socks5 udp header.
No need to have multiple relays open

**Comment by heiher** [comment]
The current practice is that one local source `address:port` pair corresponds to one connection/session, while one connection/session can communicate with multiple different destination `address:port` pairs.

**Comment by AnyPortal** [comment]
I noticed that on Android hev-socks5-tunnel is several times slower than sing-box (as tun2socks only) when opening new web pages. Haven't nailed the exact reason but then I saw this issue,

On Linux and Android, the DNS resolver in the OS use new random source port for each DNS request. Considering the nature of this tool it might be a really common usage case, and a new connection per DNS request can make the process several times slower.

Please considering (maybe an option) to reuse the connection/session for udp relay.
