### ISSUE TITLE
Mipsel_74kc support

### ISSUE THREAD

**Issue by Miraihi** [heiher/hev-socks5-tunnel#176]
Basically the title. Asus RT-N56U (Both A1 and B1) remain a pretty popular routers despite the age, but don't have much low weight and accessible tunnelling software on Openwrt that supports Socks5. Thus I wish we had Mipsel_74kc build.

**Comment by heiher** [comment]
Does mips32el or mips32elsf support it?

https://github.com/heiher/hev-socks5-tunnel/releases/download/2.7.4/hev-socks5-tunnel-linux-mips32el
https://github.com/heiher/hev-socks5-tunnel/releases/download/2.7.4/hev-socks5-tunnel-linux-mips32elsf

**Comment by Miraihi** [comment]
> Does mips32el or mips32elsf support it?
> 
> https://github.com/heiher/hev-socks5-tunnel/releases/download/2.7.4/hev-socks5-tunnel-linux-mips32el https://github.com/heiher/hev-socks5-tunnel/releases/download/2.7.4/hev-socks5-tunnel-linux-mips32elsf

Thank you, I'll test them once again and report back.

**Comment by Miraihi** [comment]
Well, I'm getting "Parse failed" message from them, but I guess this means that they work and it's all the fault of my config file.
```
root@OpenWrt:/opt/hev-socks5-tunnel# ./hev-socks5-tunnel-linux-mips32el /opt/hev
-socks5-tunnel/conf
Parse /opt/hev-socks5-tunnel/conf failed!
root@OpenWrt:/opt/hev-socks5-tunnel# ./hev-socks5-tunnel-linux-mips32elsf /opt/h
ev-socks5-tunnel/conf
Parse /opt/hev-socks5-tunnel/conf failed!
```

**Comment by heiher** [comment]
`./hev-socks5-tunnel-linux-mips32el /opt/hev-socks5-tunnel/conf/main.yml`

**Comment by Miraihi** [comment]
> `./hev-socks5-tunnel-linux-mips32el /opt/hev-socks5-tunnel/conf/main.yml`

Oh I see, my silly mistake.
It seems like `mips32elsf` works (successfully created the network device mentioned in `main.yml`) while mips32el reports `illegal instruction`. Thank you! I have a lot to learn.
