### ISSUE TITLE
post up脚本执行报错

### ISSUE THREAD

**Issue by CCCAUCHY** [heiher/hev-socks5-tunnel#182]
`./hev-socks5-tunnel-linux-arm64 tun.yaml ;./up.sh`这样运行是正常的, 但是`post-up-script: /root/up.sh`报错`[2024-11-08 14:15:43] [E] exec up.sh tun0`

```
cat up.sh
ip route add default dev tun0 table 438
ip -6 route add default dev tun0 table 438
```

**Comment by heiher** [comment]
看上去是没有设置interpreter：

```sh
#!/bin/bash
```
