### ISSUE TITLE
支持HTTP代理吗

### ISSUE THREAD

**Issue by 250king** [heiher/hev-socks5-tunnel#183]
我想做一个HTTP Hook类应用，为了简化设置代理流程就想使用tun2socks方案，但代理只支持HTTP，然后翻阅了贵项目文档好像是不支持HTTP代理，请问是这样的吗？

**Comment by heiher** [comment]
不支持。域名解析需要UDP。

**Comment by 250king** [comment]
那贵项目默认编写是支持Android 15的16kb页大小吗？其实我知道最新版NDK直接编译是可以构造16kb页大小的so，但是因为我怕出现普遍C项目对页大小写死的情况，由于我不太懂C语言，还是希望作者能帮我解答一下
