### ISSUE TITLE
[Feature Request] DNSGW

### ISSUE THREAD

**Issue by tormentous** [heiher/hev-socks5-tunnel#185]
Here's how it typically works:
 * Local DNS Server:
   * Standalone DNS Server: You can set up a local DNS server like dnsmasq or pdnsd.
   * System DNS: Configure your system's DNS settings to point to this local server.
 * Tun2socks Configuration:
   * DNS Redirection: You can configure Tun2socks to route all DNS traffic to the local DNS server. This is often done using the --dnsgw option, specifying the IP address and port of the local DNS server.
 * Local DNS Server Configuration:
   * Remote DNS: The local DNS server can be configured to forward DNS queries to remote DNS servers, such as Google DNS (8.8.8.8, 8.8.4.4) or Cloudflare DNS (1.1.1.1, 1.0.0.1).
   * DNS Filtering: You can implement DNS filtering rules on the local DNS server to block specific domains or categories of websites.
Key Benefits of This Approach:
 * Enhanced Privacy: By routing DNS queries through a local server, you can protect your privacy and prevent DNS leakage.
 * Improved Performance: A local DNS server can cache DNS responses, reducing latency and improving overall network performance.
 * Content Filtering: You can implement custom DNS filtering rules to block unwanted content.

**Comment by heiher** [comment]
This seems like a specific use case for tun2socks' built-in rule-based policy routing. I'll consider whether to support it.

**Comment by HeXis-YS** [comment]
个人强烈不建议实现udpgw和dnsgw，它们都是非常有针对性的功能。~~换句话说，是badvpn的屎山~~
udpgw是badvpn的模块。badvpn的tun2socks不支持socks5 UDP，当时对于UDP的需求可能不太大，就拿udpgw凑合了，不代表tun2socks需要这个功能。而且后续badvpn tun2socks也增加了原生UDP的支持，不过那已经是很久以后了。
dnsgw则是shadowsocks加上的，估计是为了在当时分流机制还不完善的情况下给DNS做一个初级分流。~~他们还在udpgw的基础上做了一个udp relay~~
本项目已经做好了它的工作，把流量转发到socks5端口。至于DNS分流什么的，那应该是代理服务器该做的事。

**Comment by heiher** [comment]
> 个人强烈不建议实现udpgw和dnsgw，它们都是非常有针对性的功能。~换句话说，是badvpn的屎山~ udpgw是badvpn的模块。badvpn的tun2socks不支持socks5 UDP，当时对于UDP的需求可能不太大，就拿udpgw凑合了，不代表tun2socks需要这个功能。而且后续badvpn tun2socks也增加了原生UDP的支持，不过那已经是很久以后了。 dnsgw则是shadowsocks加上的，估计是为了在当时分流机制还不完善的情况下给DNS做一个初级分流。~他们还在udpgw的基础上做了一个udp relay~ 本项目已经做好了它的工作，把流量转发到socks5端口。至于DNS分流什么的，那应该是代理服务器该做的事。

我认同你的观点。
