### ISSUE TITLE
有个请求

### ISSUE THREAD

**Issue by Yewenyu** [heiher/hev-socks5-tunnel#187]
大神，可以增加两个方法替代fd做输入输出ip包吗

**Comment by heiher** [comment]
我建议传入`socketpair`或`unix domain socket`来接收ip包。通过回调直接调外部函数读写的话，应该不太方便适配内外的IO模型。

**Comment by Yewenyu** [comment]
> 我建议传入`socketpair`或`unix domain socket`来接收ip包。通过回调直接调外部函数读写的话，应该不太方便适配内外的IO模型。

好的，我试一下

**Comment by Yewenyu** [comment]
`func createFD() -> Int32?{
            var fds = [Int32(-1),-1];
            if socketpair(AF_UNIX, SOCK_DGRAM, 0, &fds) < 0{
                perror("socketpair");
                return nil
            }
            let fd1 = fds[0]
            let fd2 = fds[1]
            func readPackets(){
                self.packetTunnel?.packetFlow.readPackets { packets, protocols in
                    for packet in packets {
                        // packet是Data类型的IP数据包
                        packet.withUnsafeBytes { (buf: UnsafeRawBufferPointer) in
                            let ptr = buf.baseAddress!
                            let len = buf.count
                            // 写入fds[0]
                            let written = write(fd1, ptr, len)
                            if written < 0 {
                                // 错误处理
                            }
                        }
                    }
                    readPackets()
                }
            }
            func writePacket(){
                DispatchQueue.global().async {
                    while true{
                        autoreleasepool {
                            var buffer = [UInt8](repeating: 0, count: 65535)
                            let bytesRead = read(fd1, &buffer, buffer.count)
                            if bytesRead > 0 {
                                let packetData = Data(buffer[0..<bytesRead])
                                self.packetTunnel?.packetFlow.writePackets([packetData], withProtocols: [AF_INET as NSNumber])
                            }
                        }
                    }
                    
                }
            }
            defer{
                readPackets()
                writePacket()
            }
            
            
            
            
            return fd2
        }
public func run(withConfig filePath: String) -> Int32 {
        guard let fileDescriptor = createFD() else {
            fatalError("Get tunnel file descriptor failed.")
        }
        
        return hev_socks5_tunnel_main(filePath.cString(using: .utf8), fileDescriptor)
    }`
        
        `tunnel:
  mtu: 9000
socks5:
  port: 7890
  address: ::1
  udp: udp
misc:
  task-stack-size: 20480
  connect-timeout: 5000
  read-write-timeout: 60000
  log-file: /Users/ye/Library/Containers/876AE2F8-451D-4CF7-B761-0AC9D01EE641/Data/Documents/tun2socks/log.log
  log-level: debug
  limit-nofile: 65535
`
`
[2024-12-06 13:05:44] [D] socks5 tunnel init
[2024-12-06 13:05:44] [D] socks5 tunnel run
[2024-12-06 13:05:44] [D] socks5 tunnel lwip task run
`
用socketpair，tun2socks没有读到任何数据

**Comment by heiher** [comment]
是不是packetTunnel.packetFlow读写的packet没有type header，导致两边不匹配？

https://github.com/heiher/hev-socks5-tunnel/blob/d46a36fbf43d1540776275315596e64c8bfe60cd/src/hev-tunnel-macos.h#L15-L28

**Comment by Yewenyu** [comment]
> HevTaskIOYielder

ios对应哪个hev-tunnel文件，我打个log看看

**Comment by heiher** [comment]
> > HevTaskIOYielder
> 
> ios对应哪个hev-tunnel文件，我打个log看看

https://github.com/heiher/hev-socks5-tunnel/blob/d46a36fbf43d1540776275315596e64c8bfe60cd/src/hev-tunnel.h#L21-L23

**Comment by Yewenyu** [comment]
```
func packIPPacket(_ ipPacket: Data) -> Data {
        guard ipPacket.count > 0 else {
            return Data()
        }
        
        // 获取 IP version (前4位)
        let version = (ipPacket[ipPacket.startIndex] >> 4) & 0x0F
        
        // 根据版本决定type
        var typeValue: UInt32 = 0
        if version == 4 {
            // IPv4
            typeValue = UInt32(AF_INET).bigEndian
        } else {
            // IPv6
            typeValue = UInt32(AF_INET6).bigEndian
        }
        
        var result = Data()
        withUnsafeBytes(of: typeValue) { result.append(contentsOf: $0) }
        result.append(ipPacket)
        
        return result
    }
    
    func unpackIPPacket(_ data: Data) -> (type: Int64, ipPacket: Data)? {
        guard data.count > 4 else {
            return nil
        }
        
        // 读出 type (4 字节)
        let typeData = data.subdata(in: 0..<4)
        var typeValue = typeData.withUnsafeBytes { $0.load(as: UInt32.self) }
        typeValue = UInt32(bigEndian: typeValue)
        
        let ipPacket = data.subdata(in: 4..<data.count)
        
        
        return (Int64(typeValue), ipPacket)
    }
```
```
[2024-12-06 17:35:53] [D] 0x14503a240 socks5 construct
[2024-12-06 17:35:53] [D] 0x14503a240 socks5 client construct
[2024-12-06 17:35:53] [I] 0x14503a240 socks5 client udp construct
[2024-12-06 17:35:53] [D] 0x14503a240 socks5 session udp construct
[2024-12-06 17:35:53] [D] 0x14503a240 socks5 session udp new

[2024-12-06 17:36:11] [D] 0x1452184d0 socks5 construct
[2024-12-06 17:36:11] [D] 0x1452184d0 socks5 client construct
[2024-12-06 17:36:11] [D] 0x1452184d0 socks5 client tcp construct ip
[2024-12-06 17:36:11] [I] 0x1452184d0 socks5 client tcp -> [103.30.76.128]:443
[2024-12-06 17:36:11] [D] 0x1452184d0 socks5 session tcp construct
[2024-12-06 17:36:11] [D] 0x1452184d0 socks5 session tcp new


```
一直重复这个日志，数据没有发到shadowsock那边

**Comment by heiher** [comment]
从日志来看，至少向hev-socks5-tunnel方向的包转发已经通了，并且校验也都正常，能正常解析出网络层的IP地址端口。但仅从这些日志看不出更多的信息，socks5服务器端是否收到连接请求？如收到请求但没有数据，则需要进一步排查双向的包转发是否都正常。

**Comment by Yewenyu** [comment]
socks5收不到连接请求



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: hev ***@***.***&gt;
发送时间: 2024年12月6日 18:11
收件人: heiher/hev-socks5-tunnel ***@***.***&gt;
抄送: Yewenyu ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [heiher/hev-socks5-tunnel] 有个请求 (Issue #187)





 
从日志来看，至少向hev-socks5-tunnel方向的包转发已经通了，并且校验也都正常，能正常解析出网络层的IP地址端口。但仅从这些日志看不出更多的信息，socks5服务器端是否收到连接请求？如收到请求但没有数据，则需要进一步排查双向的包转发是否都正常。

**Comment by heiher** [comment]
日志补充完整

**Comment by heiher** [comment]
看不出来……

**Comment by Yewenyu** [comment]
和socks5建立连接的代码在哪里

**Comment by Yewenyu** [comment]
hev_socks5_session_task_entry 没有调用这个方法

**Comment by heiher** [comment]
> hev_socks5_session_task_entry

如果hev_socks5_session_task_entry的task一直被创建，但task_entry从未能得到执行，那说明tun fd上一直有报文可读？这是一直在模拟发包吗？

**Comment by Yewenyu** [comment]
没有模拟，一直是真实的包，是一直有ip包转发到hev&nbsp;



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: hev ***@***.***&gt;
发送时间: 2024年12月9日 20:16
收件人: heiher/hev-socks5-tunnel ***@***.***&gt;
抄送: Yewenyu ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [heiher/hev-socks5-tunnel] 有个请求 (Issue #187)





  
hev_socks5_session_task_entry
  
如果hev_socks5_session_task_entry的task一直被创建，但task_entry从未能得到执行，那说明tun fd上一直有报文可读？这是一直在模拟发包吗？

**Comment by heiher** [comment]
lwip io task的优先级非常高，但如果不是一直不停的发送新的TCP SYN，也不至于会话task一直不能执行吧。感觉还是包转发哪里有问题，导致流量一直在循环？

**Comment by Yewenyu** [comment]
> lwip io task的优先级非常高，但如果不是一直不停的发送新的TCP SYN，也不至于会话task一直不能执行吧。感觉还是包转发哪里有问题，导致流量一直在循环？

```
func createFD() -> Int32? {
        var fds = [Int32(-1), -1]
        if socketpair(AF_UNIX, SOCK_STREAM, 0, &fds) < 0 {
            perror("socketpair")
            return nil
        }
        let fd1 = fds[0]
        let fd2 = fds[1]
        let tunFd = tunnelFileDescriptor ?? -1
        let mtu = 1500
        func handle(_ from:Int32,to:Int32,label:String){
            let queue = DispatchQueue.init(label: label)
            queue.async {
                var buffer = [UInt8](repeating: 0, count: mtu)
                while true {
                    let bytesRead = read(from, &buffer, buffer.count)
                    if bytesRead > 0 {
                        let receivedData = Data(buffer[0 ..< bytesRead])
                        receivedData.withUnsafeBytes { (buf: UnsafeRawBufferPointer) in
                            guard let ptr = buf.baseAddress else {
                                print("Error: combinedData has no base address")
                                return
                            }
                            let len = buf.count
                            let written = write(to, ptr, len)
                            if written < 0 {
                                perror("write failed")
                            } else if written < len {
                                print("Warning: only \(written) bytes out of \(len) were written")
                            }
                        }
                        
                    }
                }
            }
        }
        handle(tunFd, to: fd1,label: "tunfd read")
        handle(fd1, to: tunFd,label: "tunfd write")

        return fd2
    }
```
这里已经是直接从tun fd读取数据不做处理然后转发到hev
我使用同样的代码把fd传进shadowsocks-rust是正常的

**Comment by heiher** [comment]
试试只创建一个TCP连接

**Comment by Yewenyu** [comment]
> 试试只创建一个TCP连接

不明白你的意思

**Comment by heiher** [comment]
> > 试试只创建一个TCP连接
> 
> 不明白你的意思

 就是控制在 tun 网口上只跑一路TCP连接，看看转发是否都正常。（我很奇怪是什么业务能让tun口上持续有新的TCP连接在建立，并且这样的流量一刻也不停，以至于都没有时间调度执行会话任务。

**Comment by Yewenyu** [comment]
> > > 试试只创建一个TCP连接
> > 
> > 
> > 不明白你的意思
> 
> 就是控制在 tun 网口上只跑一路TCP连接，看看转发是否都正常。（我很奇怪是什么业务能让tun口上持续有新的TCP连接在建立，并且这样的流量一刻也不停，以至于都没有时间调度执行会话任务。

还是一样，不会调用hev_socks5_session_task_entry，没有和socks5建立连接
同一环境，hev直接使用tunfd是正常的，使用socketpair就不行建立不了socks5的连接

**Comment by heiher** [comment]
看看是不是传入hev-socks5-tunnel的socketpair fd没有配置为non-blocking模式 🤣

**Comment by Yewenyu** [comment]
> 看看是不是传入hev-socks5-tunnel的socketpair fd没有配置为non-blocking模式 🤣

对，配置了就可以了，但是速度慢了一倍，有什么解决方法吗

**Comment by Yewenyu** [comment]
> > > 看看是不是传入hev-socks5-tunnel的socketpair fd没有配置为non-blocking模式 🤣
> > 
> > 
> > 对，配置了就可以了，但是速度慢了一倍，有什么解决方法吗
> 
> 好。为什么不直接传入 tun fd？

因为想对ip包做一些分流和修改

**Comment by heiher** [comment]
MTU提高到8500。非要按IP包过滤流量的话不太好办，看看能不能在Socks5服务端上分流

**Comment by Yewenyu** [comment]
> MTU提高到8500。非要按IP包过滤流量的话不太好办，看看能不能在Socks5服务端上分流

hev 里面tun fd的读写逻辑可以说一下吗，我按照你的逻辑来修改看看行不行

**Comment by heiher** [comment]
> > MTU提高到8500。非要按IP包过滤流量的话不太好办，看看能不能在Socks5服务端上分流
> 
> hev 里面tun fd的读写逻辑可以说一下吗，我按照你的逻辑来修改看看行不行

从tun fd读：有一个专门的lwip io task用于从tun fd读报文，再送入lwip。
向tun fd写：由lwip的回调调用，实际上可能有两类task驱动（也就是在这些task里执行的回调）：session task、timer task。

对lwip api的操作均有mutex在多个task间同步，注意这个mutex不是线程安全的，而是协程的。

**Comment by Yewenyu** [comment]
> > > MTU提高到8500。非要按IP包过滤流量的话不太好办，看看能不能在Socks5服务端上分流
> > 
> > 
> > hev 里面tun fd的读写逻辑可以说一下吗，我按照你的逻辑来修改看看行不行
> 
> 从tun fd读：有一个专门的lwip io task用于从tun fd读报文，再送入lwip。 向tun fd写：由lwip的回调调用，实际上可能有两类task驱动（也就是在这些task里执行的回调）：session task、timer task。
> 
> 对lwip api的操作均有mutex在多个task间同步，注意这个mutex不是线程安全的，而是协程的。

lwip返回的数据会不会有包含多个ip包写进tunfd的？

**Comment by Yewenyu** [comment]
解决了，增大socketpair的缓冲区就可以了

**Comment by heiher** [comment]
> lwip返回的数据会不会有包含多个ip包写进tunfd的？

不会的。

**Comment by heiher** [comment]
> 解决了，增大socketpair的缓冲区就可以了

666
