### ISSUE TITLE
Compile static library for iOS moible

### ISSUE THREAD

**Issue by jadeHandsome** [heiher/hev-socks5-tunnel#22]
Hello, I would like to ask whether this library can be compiled for mobile client use @daemooon

**Comment by jadeHandsome** [comment]
The ios client can use the built-in module of Apple to expand and intercept the system traffic. I need a code to receive traffic analysis and forward, that is, it does not need to intercept the traffic related code. May I ask how can I split the code

**Comment by daemooon** [comment]
> Hello, I would like to ask whether this library can be compiled for mobile client use @daemooon

Sample [here](https://github.com/daemooon/Tun2SocksKit/blob/main/.github/workflows/Release.yml)

**Comment by daemooon** [comment]
> The ios client can use the built-in module of Apple to expand and intercept the system traffic. I need a code to receive traffic analysis and forward, that is, it does not need to intercept the traffic related code. May I ask how can I split the code

我想你可以使用PacketFlow对象进行数据读写，完成你的业务逻辑之后，使用PacketTunnelProvider创建UDPSession或者TCPConnection将数据发送出去。

**Comment by jadeHandsome** [comment]
说中文就好了，请问博主，方便添加微信聊聊吗，我有几个问题想请教下，我们需求是需要用s5进行流量转发

**Comment by jadeHandsome** [comment]
你的库里面的socks5的握手方式跟常规的不一样，你吧密码验证跟tcp链接合并到一起了，我想知道除此之外跟常规的s5还有什么区别吗

**Comment by heiher** [comment]
> 你的库里面的socks5的握手方式跟常规的不一样，你吧密码验证跟tcp链接合并到一起了，我想知道除此之外跟常规的s5还有什么区别吗

Socks5客户端是将握手中多个交互合并一次发送的，这样不仅可以有效减少会话建立的延迟，也可以在流量传输模式上减弱Socks5协议的特征。根据Socks5协议的设计，是有这么做的条件的，因为Socks5 header每个部分都是明确的数据长度定义，所以在TCP流上传输不能假设像UDP报文一样每次IO读出的刚好，一个能正确处理流IO读写的Socks5 server应该不会存在握手问题。除此之外，应该是完全兼容RFC1928的CONNECT和UDP ASSOCIATE方法的。

**Comment by jadeHandsome** [comment]
现在就是遇到个问题 我用你的项目吧安卓跑起来 流量转发给了服务器 握手协议改成你的这个一次性解析 其他没动 但是发现流量还是转发不出去

**Comment by heiher** [comment]
安卓可以直接拿这个测服务端：https://github.com/heiher/sockstun 先用[hev-socks5-server](https://github.com/heiher/hev-socks5-server)或xray作为服务端先跑通，然后再调别的服务端。

需要注意的是UDP转发模式：hev-socks5-server选上udp relay over tcp，其它的则不选。

之前有人反馈过握手兼容问题，是一种有多协议单端口复用的服务端，它的实现明显存在问题，数据内容上很明显的socks5协议特征都无法识别出来，看上去很可能就是流IO的处理有问题。

**Comment by jadeHandsome** [comment]
你这个可以编译使用centos的吗 我看目前只有linux跟安卓

**Comment by heiher** [comment]
centos就是linux，预编译或自行编译都可。

**Comment by jadeHandsome** [comment]
你好 博主 我这边遇到一个问题 在安卓上 访问ip能截取到ip 但是访问域名解析解析出来的ip都是 0 我想知道是我哪里的配置问题吗 安卓是用的你的demo

**Comment by heiher** [comment]
在哪里“截取”的？

**Comment by jadeHandsome** [comment]
服务端这边接收到的链接参数  0x05050001000000000000  链接指令收到的都是这个

**Comment by jadeHandsome** [comment]
如果我访问的是纯ip 接收到的就是 0x05010001c73b95e60050  就能解析出来ip

**Comment by heiher** [comment]
>  0x05[05]0001000000000000

cmd = 0x05是hev-socks5-core为了实现all in tcp而扩展的非标准的udp relay in tcp模式。
在Android客户端上去掉udp relay in tcp的勾选后再配合支持udp associate的socks5 server测试。

**Comment by jadeHandsome** [comment]
我现在就是只用你的客户端代码 不用你的服务端代码 导致的结果就是 没办法正常转发流量 udp relay in tcp这个我取消勾选过后服务端收到的全是udp指令0x05030001000000000000  我想知道这个是需要我服务端做什么处理才能拿到ip

**Comment by heiher** [comment]
对于域名访问，Android应用程序需要先发起DNS查询产生UDP报文，SocksTun建立UDP Associate会话(0x05[03])，转发DNS请求和响应；Android应用程序拿到IP后，才会建立TCP Connect会话(0x0501)。所以你的Socks5服务端需要支持UDP Associate(0503)。

**Comment by jadeHandsome** [comment]
非常感谢你的耐心讲解，我在这方面还有点生疏，以我的理解就是我在服务端实现0503指令 建立udp链接 然后客户端吧udp报文给我我转发返回 客户端就能拿到ip建立tcp对吗 如果是这样的话我想问问我现在收到的全是 0x05030001000000000000 这样一个指令相当于我需要去跟 0:0:0:0 这样一个全是0的地址建立udp吗

**Comment by heiher** [comment]
不是，UDP relay的流程阅读[RFC1928](https://www.rfc-editor.org/rfc/rfc1928)

或

看hev-socks5-core的实现:

https://github.com/heiher/hev-socks5-core/blob/master/src/hev-socks5-server.c#L546-L551
https://github.com/heiher/hev-socks5-core/blob/master/src/hev-socks5-server.c#L448-L517
https://github.com/heiher/hev-socks5-core/blob/master/src/hev-socks5-server.c#L580-L582
https://github.com/heiher/hev-socks5-core/blob/master/src/hev-socks5-udp.c#L44-L359

**Comment by jadeHandsome** [comment]
好的  感谢解答 我这边研究下 另外我问一下 通过服务端解析ip的思路是为了防止客户端的dns污染吗还是什么  因为我看tuns2socks-go 他是本地解析的ip

**Comment by heiher** [comment]
在这个层面没有特别的考虑，就是把所支持的TCP、UDP协议的全部流量用Socks5协议转发出来，把处理权交给Socks5服务端。Socks5服务端也是可以运行在客户端侧的，Socks5协议只是复用标准协议用于传递地址信息。

**Comment by jadeHandsome** [comment]
博主你好  安卓这边我已经跑起来完全没问题了 我现在还需要吧你的代码给 ios这边使用 我想得到你的帮助可以吗

**Comment by heiher** [comment]
遇到什么问题了？

**Comment by jadeHandsome** [comment]
你好 大佬 我这里现在还剩下最后 一个问题  安卓端这里  我想屏蔽ipv6的dns解析  有什么办法吗

**Comment by jadeHandsome** [comment]
不好意思 我看到了你里面可以屏蔽ipv6  最后一个问题了大佬  就是我想用java重新实现你的udprelay over tcp功能  我想大致了解下你这个的流程的实现可以给我讲一下吗

**Comment by heiher** [comment]
确定这真是最后一个问题了吗？:P

> java重新实现你的udprelay over tcp功能

收、发实现的代码在这里：https://github.com/heiher/hev-socks5-core/blob/master/src/hev-socks5-udp.c#L44-L145
