### ISSUE TITLE
可否引入 CMake 編譯系統？

### ISSUE THREAD

**Issue by ssrlive** [heiher/hev-socks5-tunnel#27]
如題，這樣的話，就可以在所有操作系統內使用同一構建命令了。

**Comment by heiher** [comment]
现在除了freebsd使用gmake，其它都是直接make即可。

**Comment by ssrlive** [comment]
項目不支持 windows 平臺？那沒必要引入 cmake 。

**Comment by heiher** [comment]
是的 😄

**Comment by ssrlive** [comment]
有計劃支持 windows 嗎，比如以 [wintun](https://www.wintun.net/) 作後端？

**Comment by ssrlive** [comment]
使用 WSL2 是開發者的玩法，不是普通用戶的玩法。好吧。多謝回覆。

**Comment by heiher** [comment]
不客气。我日常全是使用Linux桌面、服务器，也就没有考虑过Windows支持。tun方案也只是因为要跑在Android上，偏向于高效节能，至于Linux桌面、路由器首选tproxy了。

**Comment by ssrlive** [comment]
想起來了，我寫過一個windows下的 [協程庫](https://github.com/ssrlive/coroutine) ，用的是纖程函數，也許對你有些幫助。

該庫在 linux 和 windows 下均表現不錯，但蘋果家的 ios / mac 下由於 蘋果放棄了 `makecontext` 系列函數，執行是錯誤的。

**Comment by heiher** [comment]
谢谢~ 协程基础设施和调度器方面移植问题不大，一直没做移植认为的难点一是在于Windows没有使用方式类似epoll/kqueue支持事件边沿触发的机制，二是文件描述符方面也没有做抽象等等。
