### ISSUE TITLE
support rust?

### ISSUE THREAD

**Issue by FlyGGYe** [heiher/hev-socks5-tunnel#29]

**Comment by heiher** [comment]
Not currently, but it's easy to do.

**Comment by OnePiece110** [comment]
> Not currently, but it's easy to do.

Can you do it？ I want use it in rust

**Comment by OnePiece110** [comment]
> Not currently, but it's easy to do.

can you do it？

**Comment by heiher** [comment]
I will try it when i have some free time.

**Comment by heiher** [comment]
https://crates.io/crates/tun2socks
