### ISSUE TITLE
can't get FULL CONE NAT

### ISSUE THREAD

**Issue by lvlynn** [heiher/hev-socks5-tunnel#31]
1. use udp over udp , nintendo switch  get  F
2. use udp over tcp, nintendo switch  get  B
3. use udp over udp , use   pystun  test show  NAT Type: Blocked （https://github.com/jtriley/pystun）

**Comment by heiher** [comment]
The NAT type depends on server side.

**Comment by lvlynn** [comment]
My server has public IP ， and I open ALL INPUT、OUTPUT rule。 I use other socks client test NAT function.  Pystun show Full Cone， like below picture:
![1679915450364](https://user-images.githubusercontent.com/12165023/227925745-3d31ad05-f7cd-49fb-82fd-aae86ea6dd88.png)

**Comment by heiher** [comment]
Try socks5 server: https://github.com/heiher/hev-socks5-server

**Comment by lvlynn** [comment]
I've already tried "hev-socks5-server" and 3proxy project.  The result is 
1. use udp over udp , nintendo switch get F
2. use udp over tcp, nintendo switch get B
3. use udp over udp , use pystun test show NAT Type: Blocked
I think the issue arises in "hev-socks5-tunnel" client.
