### ISSUE TITLE
apk hev-socks5-tunnel

### ISSUE THREAD

**Issue by ingnelson** [heiher/hev-socks5-tunnel#4]
Hello sir.
Can you create a apk , please ? 
i am not a programmer , but i want to use hev-socks5-tunnel.

i want to install it on a ubuntu VPS for server and use android like client.

**Comment by heiher** [comment]
This is a partially public project, so it cannot be fully deployed directly.

**Comment by Kingsmanvn-Official** [comment]
> This is a partially public project, so it cannot be fully deployed directly.

@heiher can you tell me how to use the command `ndk-build`

**Comment by heiher** [comment]
@Kingsmanvn-Official Download the Android NDK from:https://developer.android.com/ndk/downloads

Now there have an Android VPN over socks5 project is based on this, you should download it from: https://github.com/heiher/sockstun
