### ISSUE TITLE
Library crash on android

### ISSUE THREAD

**Issue by evgenybozhko2** [heiher/hev-socks5-tunnel#42]
Hello, dear creators for fast and powerful lib. I have experience with Android and got a crash when trying to disconnect VPN via call 
`native_stop_service()`. Also, I have opened a browser with a large site page where some connections are active. And then the lib crashes with 100% reproducibility.  I will attache the stack crash here. Maybe you will let me understand what the issue is it. 

`$ ndk-stack -sym obj/local/armeabi-v7a -dump logcatstack.txt
********** Crash dump: **********
Build fingerprint: 'samsung/a10dd/a10:11/RP1A.200720.012/A105FDDS9CWB2:user/release-keys'
#00 0x00062de8 /apex/com.android.runtime/lib/bionic/libc.so (abort+172) (BuildId: fef5b751123147ea65bf3f4f798c9518)
#01 0x000317e3 /data/app/~~0m7d9dyDY21u6PRAD8qSXw==/com.packagename-C_NZmKME9tYhCufO9j1fmQ==/lib/arm/libhev-socks5-tunnel.so (BuildId: 46d445c04ee2ce60954873d03fcfdc580fcad3ac)
                                                                                                                               hev_task_system_wakeup_task_with_context
                                                                                                                               /Users/evgenybozhko/Projects/AppName/app/src/main/jni/hev-socks5-tunnel/third-part/hev-task-system/src/kern/core/hev-task-system-schedule.c:152:9
                                                                                                                               hev_task_system_io_poll
                                                                                                                               /Users/evgenybozhko/Projects/AppName/app/src/main/jni/hev-socks5-tunnel/third-part/hev-task-system/src/kern/core/hev-task-system-schedule.c:170:9
                                                                                                                               hev_task_system_pick_current_task
                                                                                                                               /Users/evgenybozhko/Projects/AppName/app/src/main/jni/hev-socks5-tunnel/third-part/hev-task-system/src/kern/core/hev-task-system-schedule.c:181:13
#02 0x000315dd /data/app/~~0m7d9dyDY21u6PRAD8qSXw==/com.packagename-C_NZmKME9tYhCufO9j1fmQ==/lib/arm/libhev-socks5-tunnel.so (BuildId: 46d445c04ee2ce60954873d03fcfdc580fcad3ac)
                                                                                                                               hev_task_system_schedule
                                                                                                                               /Users/evgenybozhko/Projects/AppName/app/src/main/jni/hev-socks5-tunnel/third-part/hev-task-system/src/kern/core/hev-task-system-schedule.c:234:5
#03 0x00012785 /data/app/~~0m7d9dyDY21u6PRAD8qSXw==/com.packagename-C_NZmKME9tYhCufO9j1fmQ==/lib/arm/libhev-socks5-tunnel.so (hev_socks5_tunnel_run+76) (BuildId: 46d445c04ee2ce60954873d03fcfdc580fcad3ac)
                                                                                                                               hev_socks5_tunnel_run
                                                                                                                               /Users/evgenybozhko/Projects/AppName/app/src/main/jni/hev-socks5-tunnel//src/hev-socks5-tunnel.c:192:5
#04 0x0001145b /data/app/~~0m7d9dyDY21u6PRAD8qSXw==/com.packagename-C_NZmKME9tYhCufO9j1fmQ==/lib/arm/libhev-socks5-tunnel.so (hev_socks5_tunnel_main+170) (BuildId: 46d445c04ee2ce60954873d03fcfdc580fcad3ac)
                                                                                                                               hev_socks5_tunnel_main
                                                                                                                               /Users/evgenybozhko/Projects/AppName/app/src/main/jni/hev-socks5-tunnel//src/hev-main.c:132:5
#05 0x0001139b /data/app/~~0m7d9dyDY21u6PRAD8qSXw==/com.packagename-C_NZmKME9tYhCufO9j1fmQ==/lib/arm/libhev-socks5-tunnel.so (BuildId: 46d445c04ee2ce60954873d03fcfdc580fcad3ac)
                                                                                                                               thread_handler
                                                                                                                               /Users/evgenybozhko/Projects/AppName/app/src/main/jni/hev-socks5-tunnel//src/hev-jni.c:88:5
#06 0x000aaf33 /apex/com.android.runtime/lib/bionic/libc.so (__pthread_start(void*)+40) (BuildId: fef5b751123147ea65bf3f4f798c9518)
Crash dump is completed

$ 
`

**Comment by heiher** [comment]
Thanks for reporting this issue. Could you please test this patch?

```diff
diff --git a/src/hev-socks5-tunnel.c b/src/hev-socks5-tunnel.c
index 954db72..3c093e0 100644
--- a/src/hev-socks5-tunnel.c
+++ b/src/hev-socks5-tunnel.c
@@ -490,6 +490,8 @@ lwip_io_task_entry (void *data)
             pbuf_free (buf);
         hev_task_mutex_unlock (&mutex);
     }
+
+    hev_task_del_fd (task_lwip_io, tun_fd);
 }
 
 static void
```

**Comment by tozik** [comment]
Currently we did workaround currently for andoid
to change abort to return
in follow line

```
static inline void
hev_task_system_wakeup_task_with_context (HevTaskSystemContext *ctx,
                                          HevTask *task)
{
    /* skip to wake up this task that is already in running */
    if (task->state == HEV_TASK_RUNNING)
        return;

    if (task->state == HEV_TASK_STOPPED)
        abort ();

    task->sched_key += hev_task_system_get_min_sched_key (ctx);

    hev_task_system_insert_task (ctx, task);
}
```

**Comment by heiher** [comment]
Yep, this is a valid work around. Before this [commit](https://github.com/heiher/hev-task-system/commit/33b8fb83d0f24daed8318076d16479032367130e), the control flow is just returned if the scheduler tries to wake up a stopped task. But it makes for unexpected behavior that is hard to catch.

**Comment by evgenybozhko2** [comment]
> Thanks for reporting this issue. Could you please test this patch?
> 
> ```diff
> diff --git a/src/hev-socks5-tunnel.c b/src/hev-socks5-tunnel.c
> index 954db72..3c093e0 100644
> --- a/src/hev-socks5-tunnel.c
> +++ b/src/hev-socks5-tunnel.c
> @@ -490,6 +490,8 @@ lwip_io_task_entry (void *data)
>              pbuf_free (buf);
>          hev_task_mutex_unlock (&mutex);
>      }
> +
> +    hev_task_del_fd (task_lwip_io, tun_fd);
>  }
>  
>  static void
> ```

Thank you for the response. Your fix is working for my issue. So I will left patch as is now. Thank you.
