### ISSUE TITLE
iOS not free extension thread after HevSocks5Tunnel.hev_socks5_tunnel_main(path, self.currentTunnelFileDescriptor!)

### ISSUE THREAD

**Issue by tozik** [heiher/hev-socks5-tunnel#45]
After call
`HevSocks5Tunnel.hev_socks5_tunnel_main(path, self.currentTunnelFileDescriptor!))`

Tunnel is starting and all is working. But thread is blocked, code doesn't going next.
But after trying to call Stop

SIGABRT crash, on `hev_socks5_tunnel_main` line.

Some time before all was ok.
Issue reproduce with 2.4.0 and with your latest changes in this repository.

**Comment by heiher** [comment]
Could you provide more details about this issue? such as backtrace of SIGABRT. It would be best if I could reproduce it.

**Comment by tozik** [comment]
> backtrace of SIGABRT

i can send this, cause looks like SIGABRT without any additional info

```
 26 17:48:11 nesessionmanager[221] <Notice>: NESMVPNSession[Primary Tunnel:Socks5:FACE6005-F409-4B63-9E49-B5BC1F2834CF:(null)]: config request: popping handler [(null)] (null)
Jun 26 17:48:11 UserEventAgent(com.apple.networkextension)[29] <Notice>: File Handle Maintainer listening for readable events on Network Agent Registration socket (79) C292F64D-22FF-417F-9444-8B1D9DF97A08 4DB98868-B5BA-4A1A-9BB9-10EF46847865 5 (null) agent flags 0x2
Jun 26 17:48:11 UserEventAgent(com.apple.networkextension)[29] <Notice>: File Handle Maintainer listening for readable events on Network Agent Registration socket (81) 2F2F98CE-AAC0-40FF-AC86-421317D88F96 A9C8E388-EAA9-45A9-8D8F-C90C6CD055FC 5 (null) agent flags 0x3
Jun 26 17:48:11 PacketTunnel(NetworkExtension)[4323] <Notice>: [Extension com.vpnsatoshi.vpnsatoshiapp.packet-tunnel]: Calling stopTunnelWithReason because: Stop command received
Jun 26 17:48:11 PacketTunnel(NetworkExtension)[4323] <Notice>: [Extension com.vpnsatoshi.vpnsatoshiapp.packet-tunnel]: IPC detached
Jun 26 17:48:11 SpringBoard(Network)[32] <Notice>: -[NWSystemPathMonitor updateFlags] Wi-Fi primary: true->true, Ethernet primary: false->false, VPN active: true->false
Jun 26 17:48:11 nesessionmanager[221] <Notice>: NESMVPNSession[Primary Tunnel:Socks5:FACE6005-F409-4B63-9E49-B5BC1F2834CF:(null)] in state NESMVPNSessionStateStopping: plugin NEVPNTunnelPlugin(com.vpnsatoshi.vpnsatoshiapp[inactive]) did detach from IPC
Jun 26 17:48:11 nesessionmanager[221] <Notice>: NESMVPNSession[Primary Tunnel:Socks5:FACE6005-F409-4B63-9E49-B5BC1F2834CF:(null)]: didSetStatus - 0
Jun 26 17:48:11 nesessionmanager[221] <Notice>: NESMVPNSession[Primary Tunnel:Socks5:FACE6005-F409-4B63-9E49-B5BC1F2834CF:(null)] in state NESMVPNSessionStateStopping: plugin NEVPNTunnelPlugin(com.vpnsatoshi.vpnsatoshiapp[inactive]) disconnected with reason Plugin initiated
Jun 26 17:48:11 nesessionmanager[221] <Notice>: NESMVPNSession[Primary Tunnel:Socks5:FACE6005-F409-4B63-9E49-B5BC1F2834CF:(null)] in state NESMVPNSessionStateStopping: plugin set status to disconnected
Jun 26 17:48:11 nesessionmanager[221] <Notice>: NESMVPNSession[Primary Tunnel:Socks5:FACE6005-F409-4B63-9E49-B5BC1F2834CF:(null)] in state NESMVPNSessionStateStopping: disposing all plugins
Jun 26 17:48:11 PacketTunnel(Foundation)[4323] <Notice>: 0
Jun 26 17:48:11 UserEventAgent(com.apple.networkextension)[29] <Notice>: File Handle Maintainer listening for readable events on Network Agent Registration socket (108) FACE6005-F409-4B63-9E49-B5BC1F2834CF 809E27DC-B636-4F18-A85B-4F0DD20973F0 1 (null) agent flags 0
Jun 26 17:48:11 SpringBoard(SpringBoard)[32] <Notice>: SBTelephonyManager updated usingVPN to NO
Jun 26 17:48:11 symptomsd(SymptomEvaluator)[129] <Notice>: defusing ticker tickerFatal having seen progress by flow for mDNSResponder, rxbytes 10132 duration 87.046 seconds started at time: Mon Jun 26 17:46:44 2023
Jun 26 17:48:11 nesessionmanager[221] <Notice>: NESMVPNSession[Primary Tunnel:Socks5:FACE6005-F409-4B63-9E49-B5BC1F2834CF:(null)]: Leaving state NESMVPNSessionStateStopping
Jun 26 17:48:11 nesessionmanager[221] <Notice>: NESMVPNSession[Primary Tunnel:Socks5:FACE6005-F409-4B63-9E49-B5BC1F2834CF:(null)]: Entering state NESMVPNSessionStateDisposing, timeout 5 seconds
Jun 26 17:48:11 nesessionmanager[221] <Notice>: com.vpnsatoshi.vpnsatoshiapp[1256]: disposing
Jun 26 17:48:11 PacketTunnel(NetworkExtension)[4323] <Notice>: Tearing down utun10
Jun 26 17:48:11 SpringBoard(SpringBoard)[32] <Notice>: disabling vpn
Jun 26 17:48:11 PacketTunnel(NetworkExtension)[4323] <Notice>: Tearing down utun10
Jun 26 17:48:11 PacketTunnel(NetworkExtension)[4323] <Error>: SIOCGIFMTU failed: Device not configured
Jun 26 17:48:11 PacketTunnel(NetworkExtension)[4323] <Error>: NEVirtualInterfaceAdjustReadBufferSize: interface_get_mtu failed (6), defaulting to max mtu
```

**Comment by tozik** [comment]
> Could you provide more details about this issue? such as backtrace of SIGABRT. It would be best if I could reproduce it.

i can send this, cause looks like SIGABRT without logs


```
 26 17:48:11 nesessionmanager[221] <Notice>: NESMVPNSession[Primary Tunnel:Socks5:FACE6005-F409-4B63-9E49-B5BC1F2834CF:(null)]: config request: popping handler [(null)] (null)
Jun 26 17:48:11 UserEventAgent(com.apple.networkextension)[29] <Notice>: File Handle Maintainer listening for readable events on Network Agent Registration socket (79) C292F64D-22FF-417F-9444-8B1D9DF97A08 4DB98868-B5BA-4A1A-9BB9-10EF46847865 5 (null) agent flags 0x2
Jun 26 17:48:11 UserEventAgent(com.apple.networkextension)[29] <Notice>: File Handle Maintainer listening for readable events on Network Agent Registration socket (81) 2F2F98CE-AAC0-40FF-AC86-421317D88F96 A9C8E388-EAA9-45A9-8D8F-C90C6CD055FC 5 (null) agent flags 0x3
Jun 26 17:48:11 PacketTunnel(NetworkExtension)[4323] <Notice>: [Extension com.appname.appnameapp.packet-tunnel]: Calling stopTunnelWithReason because: Stop command received
Jun 26 17:48:11 PacketTunnel(NetworkExtension)[4323] <Notice>: [Extension com.appname.appnameapp.packet-tunnel]: IPC detached
Jun 26 17:48:11 SpringBoard(Network)[32] <Notice>: -[NWSystemPathMonitor updateFlags] Wi-Fi primary: true->true, Ethernet primary: false->false, VPN active: true->false
Jun 26 17:48:11 nesessionmanager[221] <Notice>: NESMVPNSession[Primary Tunnel:Socks5:FACE6005-F409-4B63-9E49-B5BC1F2834CF:(null)] in state NESMVPNSessionStateStopping: plugin NEVPNTunnelPlugin(com.appname.appnameapp[inactive]) did detach from IPC
Jun 26 17:48:11 nesessionmanager[221] <Notice>: NESMVPNSession[Primary Tunnel:Socks5:FACE6005-F409-4B63-9E49-B5BC1F2834CF:(null)]: didSetStatus - 0
Jun 26 17:48:11 nesessionmanager[221] <Notice>: NESMVPNSession[Primary Tunnel:Socks5:FACE6005-F409-4B63-9E49-B5BC1F2834CF:(null)] in state NESMVPNSessionStateStopping: plugin NEVPNTunnelPlugin(com.appname.appnameapp[inactive]) disconnected with reason Plugin initiated
Jun 26 17:48:11 nesessionmanager[221] <Notice>: NESMVPNSession[Primary Tunnel:Socks5:FACE6005-F409-4B63-9E49-B5BC1F2834CF:(null)] in state NESMVPNSessionStateStopping: plugin set status to disconnected
Jun 26 17:48:11 nesessionmanager[221] <Notice>: NESMVPNSession[Primary Tunnel:Socks5:FACE6005-F409-4B63-9E49-B5BC1F2834CF:(null)] in state NESMVPNSessionStateStopping: disposing all plugins
Jun 26 17:48:11 PacketTunnel(Foundation)[4323] <Notice>: 0
Jun 26 17:48:11 UserEventAgent(com.apple.networkextension)[29] <Notice>: File Handle Maintainer listening for readable events on Network Agent Registration socket (108) FACE6005-F409-4B63-9E49-B5BC1F2834CF 809E27DC-B636-4F18-A85B-4F0DD20973F0 1 (null) agent flags 0
Jun 26 17:48:11 SpringBoard(SpringBoard)[32] <Notice>: SBTelephonyManager updated usingVPN to NO
Jun 26 17:48:11 symptomsd(SymptomEvaluator)[129] <Notice>: defusing ticker tickerFatal having seen progress by flow for mDNSResponder, rxbytes 10132 duration 87.046 seconds started at time: Mon Jun 26 17:46:44 2023
Jun 26 17:48:11 nesessionmanager[221] <Notice>: NESMVPNSession[Primary Tunnel:Socks5:FACE6005-F409-4B63-9E49-B5BC1F2834CF:(null)]: Leaving state NESMVPNSessionStateStopping
Jun 26 17:48:11 nesessionmanager[221] <Notice>: NESMVPNSession[Primary Tunnel:Socks5:FACE6005-F409-4B63-9E49-B5BC1F2834CF:(null)]: Entering state NESMVPNSessionStateDisposing, timeout 5 seconds
Jun 26 17:48:11 nesessionmanager[221] <Notice>: com.appname.appnameapp[1256]: disposing
Jun 26 17:48:11 PacketTunnel(NetworkExtension)[4323] <Notice>: Tearing down utun10
Jun 26 17:48:11 SpringBoard(SpringBoard)[32] <Notice>: disabling vpn
Jun 26 17:48:11 PacketTunnel(NetworkExtension)[4323] <Notice>: Tearing down utun10
Jun 26 17:48:11 PacketTunnel(NetworkExtension)[4323] <Error>: SIOCGIFMTU failed: Device not configured
Jun 26 17:48:11 PacketTunnel(NetworkExtension)[4323] <Error>: NEVirtualInterfaceAdjustReadBufferSize: interface_get_mtu failed (6), defaulting to max mtu

```

**Comment by tozik** [comment]
> Any more?
> 
> Could you provide stack backtrace like this: #43

until can't pull out the backstage

**Comment by tozik** [comment]
Hello @heiher 
getting back to you, maybe with helpful information
did some tests and see much exceptions, when user try to stop packet tunnel.

hope this screenshot give some information.

FYI build is not last, cause last, don't free thread, after start, and crashing mostly each time when user trying to close.

in nearest time, try to provide you some information

<img width="1021" alt="Screenshot 2023-08-08 at 02 20 53" src="https://github.com/heiher/hev-socks5-tunnel/assets/18100033/20e64ba8-a472-4a0d-9a5a-1e7dc8679273">

**Comment by tozik** [comment]
@heiher 
here is some logs, maybe there are will helpful too

`libsystem_malloc.dylib
tiny_malloc_from_free_list
libsystem_malloc.dylib
szone_malloc_should_clear
libsystem_malloc.dylib
nanov2_realloc
libsystem_malloc.dylib
malloc_zone_realloc
libsystem_malloc.dylib
realloc
libsystem_c.dylib
reallocf
libsystem_c.dylib
__sfvwrite
libsystem_c.dylib
__vfprintf
libsystem_c.dylib
_vasprintf
libsystem_c.dylib
asprintf
Network
nw_path_copy_description
Network
-[NWConcrete_nw_path description]
Foundation
_NS_os_log_callback
libsystem_trace.dylib
_os_log_fmt_flatten_NSCF
libsystem_trace.dylib
_os_log_fmt_flatten_object
libsystem_trace.dylib
_os_log_impl_flatten_and_send
Network
nw_endpoint_handler_get_alternate_path_state
Network
nw_connection_update_better_path_locked_on_nw_queue
Network
__nw_connection_endpoint_report_dry_run_on_nw_queue_block_invoke
Network
nw_connection_endpoint_report_dry_run_on_nw_queue
Network
nw_endpoint_handler_report
Network
-[NWConcrete_nw_endpoint_flow updatePathWithHandler:]
Network
nw_endpoint_handler_path_change
Network
__nw_endpoint_handler_initialize_association_block_invoke
Network
__nw_association_update_paths_block_invoke.74
Network
nw_hash_table_apply
Network
nw_association_update_paths
Network
nw_path_necp_update_evaluator
Network
nw_path_necp_check_for_updates
Network
nw_path_evaluator_force_update
Network
nw_association_activate
Network
nw_association_register
Network
nw_endpoint_handler_initialize_association
Network
nw_endpoint_handler_start
Network
nw_endpoint_flow_setup_protocols
Network
-[NWConcrete_nw_endpoint_flow startWithHandler:]
Network
nw_endpoint_handler_path_change
Network
__nw_endpoint_handler_initialize_association_block_invoke
Network
__nw_association_update_paths_block_invoke_2
Network
nw_hash_table_apply
Network
nw_association_update_paths
Network
nw_path_necp_update_evaluator
Network
nw_path_necp_check_for_updates
Network
nw_path_evaluator_force_update
Network
nw_association_activate
Network
nw_association_register
Network
nw_endpoint_handler_initialize_association
Network
nw_endpoint_handler_start
Network
nw_endpoint_flow_setup_protocols
Network
-[NWConcrete_nw_endpoint_flow startWithHandler:]
Network
nw_endpoint_handler_path_change
Network
__nw_endpoint_handler_initialize_association_block_invoke
Network
__nw_association_update_paths_block_invoke_2
Network
nw_hash_table_apply
Network
nw_association_update_paths
Network
nw_path_necp_update_evaluator
Network
nw_path_necp_check_for_updates
Network
nw_path_evaluator_force_update
Network
nw_association_activate
Network
nw_association_register
Network
nw_endpoint_handler_initialize_association
Network
nw_endpoint_handler_start
Network
nw_endpoint_flow_setup_protocols
Network
-[NWConcrete_nw_endpoint_flow startWithHandler:]
Network
nw_endpoint_handler_path_change
Network
__nw_endpoint_handler_initialize_association_block_invoke
Network
__nw_association_update_paths_block_invoke_2
Network
nw_hash_table_apply
Network
nw_association_update_paths
Network
nw_path_necp_update_evaluator
Network
nw_path_necp_check_for_updates
Network
nw_path_evaluator_force_update
Network
nw_association_activate
Network
nw_association_register
Network
nw_endpoint_handler_initialize_association
Network
nw_endpoint_handler_start
Network
nw_endpoint_flow_setup_protocols
Network
-[NWConcrete_nw_endpoint_flow startWithHandler:]
Network
nw_endpoint_handler_path_change
Network
__nw_endpoint_handler_initialize_association_block_invoke
Network
__nw_association_update_paths_block_invoke_2
Network
nw_hash_table_apply
Network
nw_association_update_paths
Network
nw_path_necp_update_evaluator
Network
nw_path_necp_check_for_updates
Network
nw_path_evaluator_force_update
Network
nw_association_activate
Network
nw_association_register
Network
nw_endpoint_handler_initialize_association
Network
nw_endpoint_handler_start
Network
nw_endpoint_flow_setup_protocols
Network
-[NWConcrete_nw_endpoint_flow startWithHandler:]
Network
nw_endpoint_handler_path_change
Network
__nw_endpoint_handler_initialize_association_block_invoke
Network
__nw_association_update_paths_block_invoke_2
Network
nw_hash_table_apply
Network
nw_association_update_paths
Network
nw_path_necp_update_evaluator
Network
nw_path_necp_check_for_updates
Network
nw_path_evaluator_force_update
Network
nw_association_activate
Network
nw_association_register
Network
nw_endpoint_handler_initialize_association
Network
nw_endpoint_handler_start
Network
nw_endpoint_flow_setup_protocols
Network
-[NWConcrete_nw_endpoint_flow startWithHandler:]
Network
nw_endpoint_handler_path_change
Network
__nw_endpoint_handler_initialize_association_block_invoke
Network
__nw_association_update_paths_block_invoke_2
Network
nw_hash_table_apply
Network
nw_association_update_paths
Network
nw_path_necp_update_evaluator
Network
nw_path_necp_check_for_updates
Network
nw_path_evaluator_force_update
Network
nw_association_activate
Network
nw_association_register
Network
nw_endpoint_handler_initialize_association
Network
nw_endpoint_handler_start
Network
nw_endpoint_flow_setup_protocols
Network
-[NWConcrete_nw_endpoint_flow startWithHandler:]
Network
nw_endpoint_handler_path_change
Network
__nw_endpoint_handler_initialize_association_block_invoke
Network
__nw_association_update_paths_block_invoke_2
Network
nw_hash_table_apply
Network
nw_association_update_paths
Network
nw_path_necp_update_evaluator
Network
nw_path_necp_check_for_updates
Network
nw_path_evaluator_force_update
Network
nw_association_activate
Network
nw_association_register
Network
nw_endpoint_handler_initialize_association
Network
nw_endpoint_handler_start
Network
nw_endpoint_flow_setup_protocols
Network
-[NWConcrete_nw_endpoint_flow startWithHandler:]
Network
nw_endpoint_handler_path_change
Network
__nw_endpoint_handler_initialize_association_block_invoke
Network
__nw_association_update_paths_block_invoke_2
Network
nw_hash_table_apply
Network
nw_association_update_paths
Network
nw_path_necp_update_evaluator
Network
nw_path_necp_check_for_updates
Network
nw_path_evaluator_force_update
Network
nw_association_activate
Network
nw_association_register
Network
nw_endpoint_handler_initialize_association
Network
nw_endpoint_handler_start
Network
nw_endpoint_flow_setup_protocols
Network
-[NWConcrete_nw_endpoint_flow startWithHandler:]
Network
nw_endpoint_handler_path_change
Network
__nw_endpoint_handler_initialize_association_block_invoke
Network
__nw_association_update_paths_block_invoke_2
Network
nw_hash_table_apply
Network
nw_association_update_paths
Network
nw_path_necp_update_evaluator
Network
nw_path_necp_check_for_updates
Network
nw_path_evaluator_force_update
Network
nw_association_activate
Network
nw_association_register
Network
nw_endpoint_handler_initialize_association
Network
nw_endpoint_handler_start
Network
nw_endpoint_flow_setup_protocols
Network
-[NWConcrete_nw_endpoint_flow startWithHandler:]
Network
nw_endpoint_handler_path_change
Network
__nw_endpoint_handler_initialize_association_block_invoke
Network
__nw_association_update_paths_block_invoke_2
Network
nw_hash_table_apply
Network
nw_association_update_paths
Network
nw_path_necp_update_evaluator
Network
nw_path_necp_check_for_updates
Network
nw_path_evaluator_force_update
Network
nw_association_activate
Network
nw_association_register
Network
nw_endpoint_handler_initialize_association
Network
nw_endpoint_handler_start
Network
nw_endpoint_flow_setup_protocols
Network
-[NWConcrete_nw_endpoint_flow startWithHandler:]
Network
nw_endpoint_handler_path_change
Network
__nw_endpoint_handler_initialize_association_block_invoke
Network
__nw_association_update_paths_block_invoke_2
Network
nw_hash_table_apply
Network
nw_association_update_paths
Network
nw_path_necp_update_evaluator
Network
nw_path_necp_check_for_updates
Network
nw_path_evaluator_force_update
Network
nw_association_activate
Network
nw_association_register
Network
nw_endpoint_handler_initialize_association
Network
nw_endpoint_handler_start
Network
nw_endpoint_flow_setup_protocols
Network
-[NWConcrete_nw_endpoint_flow startWithHandler:]
Network
nw_endpoint_handler_path_change
Network
__nw_endpoint_handler_initialize_association_block_invoke
Network
__nw_association_update_paths_block_invoke_2
Network
nw_hash_table_apply
Network
nw_association_update_paths
Network
nw_path_necp_update_evaluator
Network
nw_path_necp_check_for_updates
Network
nw_path_evaluator_force_update
Network
nw_association_activate
Network
nw_association_register
Network
nw_endpoint_handler_initialize_association
Network
nw_endpoint_handler_start
Network
nw_endpoint_flow_setup_protocols
Network
-[NWConcrete_nw_endpoint_flow startWithHandler:]
Network
nw_endpoint_handler_path_change
Network
__nw_endpoint_handler_initialize_association_block_invoke
Network
__nw_association_update_paths_block_invoke_2
Network
nw_hash_table_apply
Network
nw_association_update_paths
Network
nw_path_necp_update_evaluator
Network
nw_path_necp_check_for_updates
Network
nw_path_evaluator_force_update
Network
nw_association_activate
Network
nw_association_register
Network
nw_endpoint_handler_initialize_association
Network
nw_endpoint_handler_start
Network
nw_endpoint_flow_setup_protocols
Network
-[NWConcrete_nw_endpoint_flow startWithHandler:]
Network
nw_endpoint_handler_path_change
Network
__nw_endpoint_handler_initialize_association_block_invoke
Network
__nw_association_update_paths_block_invoke_2
Network
nw_hash_table_apply
Network
nw_association_update_paths
Network
nw_path_necp_update_evaluator
Network
nw_path_necp_check_for_updates
Network
nw_path_evaluator_force_update
Network
nw_association_activate
Network
nw_association_register
Network
nw_endpoint_handler_initialize_association
Network
nw_endpoint_handler_start
Network
nw_endpoint_flow_setup_protocols
Network
-[NWConcrete_nw_endpoint_flow startWithHandler:]
Network
nw_endpoint_handler_path_change
Network
__nw_endpoint_handler_initialize_association_block_invoke
Network
__nw_association_update_paths_block_invoke_2
Network
nw_hash_table_apply
Network
nw_association_update_paths
Network
nw_path_necp_update_evaluator
Network
nw_path_necp_check_for_updates
Network
nw_path_evaluator_force_update
Network
nw_association_activate
Network
nw_association_register
Network
nw_endpoint_handler_initialize_association
Network
nw_endpoint_handler_start
Network
nw_endpoint_flow_setup_protocols
Network
-[NWConcrete_nw_endpoint_flow startWithHandler:]
Network
nw_endpoint_handler_path_change
Network
__nw_endpoint_handler_initialize_association_block_invoke
Network
__nw_association_update_paths_block_invoke_2
Network
nw_hash_table_apply
Network
nw_association_update_paths
Network
nw_path_necp_update_evaluator
Network
nw_path_necp_check_for_updates
Network
nw_path_evaluator_force_update
Network
nw_association_activate
Network
nw_association_register
Network
nw_endpoint_handler_initialize_association
Network
nw_endpoint_handler_start
Network
nw_endpoint_flow_setup_protocols
Network
-[NWConcrete_nw_endpoint_flow startWithHandler:]
Network
nw_endpoint_handler_path_change
Network
__nw_endpoint_handler_initialize_association_block_invoke
Network
__nw_association_update_paths_block_invoke_2
Network
nw_hash_table_apply
Network
nw_association_update_paths
Network
nw_path_necp_update_evaluator
Network
nw_path_necp_check_for_updates
Network
nw_path_evaluator_force_update
Network
nw_association_activate
Network
nw_association_register
Network
nw_endpoint_handler_initialize_association
Network
nw_endpoint_handler_start
Network
nw_endpoint_flow_setup_protocols
Network
-[NWConcrete_nw_endpoint_flow startWithHandler:]
Network
nw_endpoint_handler_path_change
Network
__nw_endpoint_handler_initialize_association_block_invoke
Network
__nw_association_update_paths_block_invoke_2
Network
nw_hash_table_apply
Network
nw_association_update_paths
Network
nw_path_necp_update_evaluator
Network
nw_path_necp_check_for_updates
Network
nw_path_evaluator_force_update
Network
nw_association_activate
Network
nw_association_register
Network
nw_endpoint_handler_initialize_association
Network
nw_endpoint_handler_start
Network
nw_endpoint_flow_setup_protocols
Network
-[NWConcrete_nw_endpoint_flow startWithHandler:]
Network
nw_endpoint_handler_path_change
Network
__nw_endpoint_handler_initialize_association_block_invoke
Network
__nw_association_update_paths_block_invoke_2
Network
nw_hash_table_apply
Network
nw_association_update_paths
Network
nw_path_necp_update_evaluator
Network
nw_path_necp_check_for_updates
Network
nw_path_evaluator_force_update
Network
nw_association_activate
Network
nw_association_register
Network
nw_endpoint_handler_initialize_association
Network
nw_endpoint_handler_start
Network
nw_endpoint_flow_setup_protocols
Network
-[NWConcrete_nw_endpoint_flow startWithHandler:]
Network
nw_endpoint_handler_path_change
Network
__nw_endpoint_handler_initialize_association_block_invoke
Network
__nw_association_update_paths_block_invoke_2
Network
nw_hash_table_apply
Network
nw_association_update_paths
Network
nw_path_necp_update_evaluator
Network
nw_path_necp_check_for_updates
Network
nw_path_evaluator_force_update
Network
nw_association_activate
Network
nw_association_register
Network
nw_endpoint_handler_initialize_association
Network
nw_endpoint_handler_start
Network
nw_endpoint_flow_setup_protocols
Network
-[NWConcrete_nw_endpoint_flow startWithHandler:]
Network
nw_endpoint_handler_path_change
Network
__nw_endpoint_handler_initialize_association_block_invoke
Network
__nw_association_update_paths_block_invoke_2
Network
nw_hash_table_apply
Network
nw_association_update_paths
Network
nw_path_necp_update_evaluator
Network
nw_path_necp_check_for_updates
Network
nw_path_evaluator_force_update
Network
nw_association_activate
Network
nw_association_register
Network
nw_endpoint_handler_initialize_association
Network
nw_endpoint_handler_start
Network
nw_endpoint_flow_setup_protocols
Network
-[NWConcrete_nw_endpoint_flow startWithHandler:]
Network
nw_endpoint_handler_path_change
Network
__nw_endpoint_handler_initialize_association_block_invoke
Network
__nw_association_update_paths_block_invoke_2
Network
nw_hash_table_apply
Network
nw_association_update_paths
Network
nw_path_necp_update_evaluator
Network
nw_path_necp_check_for_updates
Network
nw_path_evaluator_force_update
Network
nw_association_activate
Network
nw_association_register
Network
nw_endpoint_handler_initialize_association
Network
nw_endpoint_handler_start
Network
nw_endpoint_flow_setup_protocols
Network
-[NWConcrete_nw_endpoint_flow startWithHandler:]
Network
nw_endpoint_handler_path_change
Network
__nw_endpoint_handler_initialize_association_block_invoke
Network
__nw_association_update_paths_block_invoke_2
Network
nw_hash_table_apply
Network
nw_association_update_paths
Network
nw_path_necp_update_evaluator
Network
nw_path_necp_check_for_updates
Network
nw_path_evaluator_force_update
Network
nw_association_activate
Network
nw_association_register
Network
nw_endpoint_handler_initialize_association
Network
nw_endpoint_handler_start
Network
nw_endpoint_flow_setup_protocols
Network
-[NWConcrete_nw_endpoint_flow startWithHandler:]
Network
nw_endpoint_handler_path_change
Network
__nw_endpoint_handler_initialize_association_block_invoke
Network
__nw_association_update_paths_block_invoke_2
Network
nw_hash_table_apply
Network
nw_association_update_paths
Network
nw_path_necp_update_evaluator
Network
nw_path_necp_check_for_updates
Network
nw_path_evaluator_force_update
Network
nw_association_activate
Network
nw_association_register
Network
nw_endpoint_handler_initialize_association
Network
nw_endpoint_handler_start
Network
nw_endpoint_flow_setup_protocols
Network
-[NWConcrete_nw_endpoint_flow startWithHandler:]
Network
nw_endpoint_handler_path_change
Network
__nw_endpoint_handler_initialize_association_block_invoke
Network
__nw_association_update_paths_block_invoke_2
Network
nw_hash_table_apply
Network
nw_association_update_paths
Network
nw_path_necp_update_evaluator
Network
nw_path_necp_check_for_updates
Network
nw_path_evaluator_force_update
Network
nw_association_activate
Network
nw_association_register
Network
nw_endpoint_handler_initialize_association
Network
nw_endpoint_handler_start
Network
nw_endpoint_flow_setup_protocols
Network
-[NWConcrete_nw_endpoint_flow startWithHandler:]
Network
nw_endpoint_handler_path_change
Network
__nw_endpoint_handler_initialize_association_block_invoke
Network
__nw_association_update_paths_block_invoke_2
Network
nw_hash_table_apply
Network
nw_association_update_paths
Network
nw_path_necp_update_evaluator
Network
nw_path_necp_check_for_updates
Network
nw_path_evaluator_force_update
Network
nw_association_activate
Network
nw_association_register
Network
nw_endpoint_handler_initialize_association
Network
nw_endpoint_handler_start
Network
nw_endpoint_flow_setup_protocols
Network
-[NWConcrete_nw_endpoint_flow startWithHandler:]
Network
nw_endpoint_handler_path_change
Network
__nw_endpoint_handler_initialize_association_block_invoke
Network
__nw_association_update_paths_block_invoke_2
Network
nw_hash_table_apply
Network
nw_association_update_paths
Network
nw_path_necp_update_evaluator
Network
nw_path_necp_check_for_updates
Network
nw_path_evaluator_force_update
Network
nw_association_activate
Network
nw_association_register
Network
nw_endpoint_handler_initialize_association
Network
nw_endpoint_handler_start
Network
nw_endpoint_flow_setup_protocols
Network
-[NWConcrete_nw_endpoint_flow startWithHandler:]
Network
nw_endpoint_handler_path_change
Network
__nw_endpoint_handler_initialize_association_block_invoke
Network
__nw_association_update_paths_block_invoke_2
Network
nw_hash_table_apply
Network
nw_association_update_paths
Network
nw_path_necp_update_evaluator
Network
nw_path_necp_check_for_updates
Network
nw_path_evaluator_force_update
Network
nw_association_activate
Network
nw_association_register
Network
nw_endpoint_handler_initialize_association
Network
nw_endpoint_handler_start
Network
nw_endpoint_flow_setup_protocols
Network
-[NWConcrete_nw_endpoint_flow startWithHandler:]
Network
nw_endpoint_handler_path_change
Network
__nw_endpoint_handler_initialize_association_block_invoke
Network
__nw_association_update_paths_block_invoke_2
Network
nw_hash_table_apply
Network
nw_association_update_paths
Network
nw_path_necp_update_evaluator
Network
nw_path_necp_check_for_updates
Network
nw_path_evaluator_force_update
Network
nw_association_activate
Network
nw_association_register
Network
nw_endpoint_handler_initialize_association
Network
nw_endpoint_handler_start
Network
nw_endpoint_flow_setup_protocols
Network
-[NWConcrete_nw_endpoint_flow startWithHandler:]
Network
nw_endpoint_handler_path_change
Network
__nw_endpoint_handler_initialize_association_block_invoke
Network
__nw_association_update_paths_block_invoke_2
Network
nw_hash_table_apply
Network
nw_association_update_paths
Network
nw_path_necp_update_evaluator
Network
nw_path_necp_check_for_updates
Network
nw_path_evaluator_force_update
Network
nw_association_activate
Network
nw_association_register
Network
nw_endpoint_handler_initialize_association
Network
nw_endpoint_handler_start
Network
nw_endpoint_flow_setup_protocols
Network
-[NWConcrete_nw_endpoint_flow startWithHandler:]
Network
nw_endpoint_handler_path_change
Network
__nw_endpoint_handler_initialize_association_block_invoke
Network
__nw_association_update_paths_block_invoke_2
Network
nw_hash_table_apply
Network
nw_association_update_paths
Network
nw_path_necp_update_evaluator
Network
nw_path_necp_check_for_updates
Network
nw_path_evaluator_force_update
Network
nw_association_activate
Network
nw_association_register
Network
nw_endpoint_handler_initialize_association
Network
nw_endpoint_handler_start
Network
nw_endpoint_flow_setup_protocols
Network
-[NWConcrete_nw_endpoint_flow startWithHandler:]
Network
nw_endpoint_handler_path_change
Network
__nw_endpoint_handler_initialize_association_block_invoke
Network
__nw_association_update_paths_block_invoke_2
Network
nw_hash_table_apply
Network
nw_association_update_paths
Network
nw_path_necp_update_evaluator
Network
nw_path_necp_check_for_updates
Network
nw_path_evaluator_force_update
Network
nw_association_activate
Network
nw_association_register
Network
nw_endpoint_handler_initialize_association
Network
nw_endpoint_handler_start
Network
nw_endpoint_flow_setup_protocols
Network
-[NWConcrete_nw_endpoint_flow startWithHandler:]
Network
nw_endpoint_handler_path_change
Network
__nw_endpoint_handler_initialize_association_block_invoke
Network
__nw_association_update_paths_block_invoke_2
Network
nw_hash_table_apply
Network
nw_association_update_paths
Network
nw_path_necp_update_evaluator
Network
nw_path_necp_check_for_updates
Network
nw_path_evaluator_force_update
Network
nw_association_activate
Network
nw_association_register
Network
nw_endpoint_handler_initialize_association
Network
nw_endpoint_handler_start
Network
nw_endpoint_flow_setup_protocols
Network
-[NWConcrete_nw_endpoint_flow startWithHandler:]
Network
nw_endpoint_handler_path_change
Network
__nw_endpoint_handler_initialize_association_block_invoke
Network
__nw_association_update_paths_block_invoke_2
Network
nw_hash_table_apply
Network
nw_association_update_paths
Network
nw_path_necp_update_evaluator
Network
nw_path_necp_check_for_updates
Network
nw_path_evaluator_force_update
Network
nw_association_activate
Network
nw_association_register
Network
nw_endpoint_handler_initialize_association
Network
nw_endpoint_handler_start
Network
nw_endpoint_flow_setup_protocols
Network
-[NWConcrete_nw_endpoint_flow startWithHandler:]`
