### ISSUE TITLE
Can't get to work in lxd ubuntu container

### ISSUE THREAD

**Issue by MikeAlinov** [heiher/hev-socks5-tunnel#49]
Hi!

I've compiled and installed everything correctly. The utility seems to be working just fine and I have created a service for it. 

But when I try to IP route all of the traffic to tun0 there is no network connection.

When I run "curl ifconfig.me," it prints out "curl: (56) Recv failure: Connection reset by peer."

I am trying to connect to the working, paid remote socks5 server that is pinging perfectly fine.

Can you please help me out here?

Thanks in advance.

**Comment by heiher** [comment]
Did you bypass the socks server?

```bash
# Bypass upstream socks5 server
sudo ip route add SOCKS5_SERVER dev DEFAULT_IFACE metric 10
sudo ip -6 route add SOCKS5_SERVER dev DEFAULT_IFACE metric 10

# Route others
sudo ip route add default dev tun0 metric 20
sudo ip -6 route add default dev tun0 metric 20
```

**Comment by hosseinkhojany** [comment]
how to find this DEFAULT_IFACE

**Comment by hosseinkhojany** [comment]
ifconfig -a
enp1s0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        ether   txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 40090  bytes 3398078 (3.3 MB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 40090  bytes 3398078 (3.3 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

wlp0s20f3: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet   netmask   broadcast 
        inet6   prefixlen 64  scopeid 0x20<link>
        ether   txqueuelen 1000  (Ethernet)
        RX packets 75332  bytes 98686805 (98.6 MB)
        RX errors 0  dropped 39  overruns 0  frame 0
        TX packets 41455  bytes 6475535 (6.4 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

**Comment by heiher** [comment]
```
$ ip route
default via 192.168.0.1 dev enp2s0 proto dhcp src 192.168.0.36 metric 100 <--- This is default iface: enp2s0
192.168.0.0/24 dev enp2s0 proto kernel scope link src 192.168.0.36 metric 100 
```

**Comment by hosseinkhojany** [comment]
[2023-07-29 05:06:07] [D] socks5 tunnel init
[2023-07-29 05:06:07] [D] socks5 tunnel run
[2023-07-29 05:06:07] [D] socks5 tunnel lwip task run
[2023-07-29 05:06:07] [D] socks5 tunnel timer task run
[2023-07-29 05:06:07] [D] socks5 tunnel event task run
[2023-07-29 05:06:35] [D] 0x5598870b90d0 socks5 construct
[2023-07-29 05:06:35] [D] 0x5598870b90d0 socks5 client construct
[2023-07-29 05:06:35] [I] 0x5598870b90d0 socks5 client udp construct
[2023-07-29 05:06:35] [D] 0x5598870b90d0 socks5 session udp construct
[2023-07-29 05:06:35] [D] 0x5598870b90d0 socks5 session udp new
[2023-07-29 05:06:35] [D] 0x5598870b90d0 socks5 session run
[2023-07-29 05:06:35] [D] 0x5598870b90d0 socks5 client connect [::1]:10801
[2023-07-29 05:06:35] [D] 0x5598870b90d0 socks5 client connect server
[2023-07-29 05:06:35] [D] 0x5598870b90d0 socks5 client connect server fd 10
[2023-07-29 05:06:35] [D] 0x5598870b90d0 socks5 client handshake
[2023-07-29 05:06:35] [D] 0x5598870b90d0 socks5 client write request
[2023-07-29 05:06:35] [D] 0x5598870b90d0 socks5 client read response
[2023-07-29 05:06:35] [E] 0x5598870b90d0 socks5 client res.rep 7
[2023-07-29 05:06:35] [E] 0x5598870b90d0 socks5 session handshake
[2023-07-29 05:06:35] [D] 0x5598870b90d0 socks5 session udp destruct
[2023-07-29 05:06:35] [D] 0x5598870b90d0 socks5 client udp destruct
[2023-07-29 05:06:35] [D] 0x5598870b90d0 socks5 client destruct
[2023-07-29 05:06:35] [D] 0x5598870b90d0 socks5 destruct

**Comment by heiher** [comment]
Show me your socks5-tunnel config.

**Comment by heiher** [comment]
Set socks5.udp = 'udp':

```
tunnel:
  name: tun888
  mtu: 1500
socks5:
  port: 10801
  address: ::1
  udp: 'udp'
misc:
  task-stack-size: 20480
  connect-timeout: 5000
  read-write-timeout: 60000
  log-file: stderr
  log-level: debug
  limit-nofile: 65535
```

**Comment by heiher** [comment]
168.119.61.1 Is this your upstream server? If yes, I think it is ok:

```
sudo ip route add 168.119.61.1 dev enp1s0 metric 10 # metric value less than tunnel's route rule
```

**Comment by hosseinkhojany** [comment]
Yes I set it metric to 10 and tunnel is 20 and set tcp to udp in tunnel config but still it not working

**Comment by heiher** [comment]
Yes, I can confirm it works with xray core. Have you tested TCP only without DNS (any UDP)?

```
curl -i 1.1.1.1
```

**Comment by hosseinkhojany** [comment]
https://github.com/heiher/hev-socks5-tunnel/assets/37432839/0d2f5a19-3881-4659-88af-52fa398111cc

**Comment by heiher** [comment]
> curl -i 1.1.1.1

Test TCP first

**Comment by hosseinkhojany** [comment]
curl -i 1.1.1.1
curl: (52) Empty reply from server

**Comment by hosseinkhojany** [comment]
IMO this issue is from xray config routing 
I removed routing element from config

**Comment by MikeAlinov** [comment]
Yeh, I didn't quite understand what this "upstream proxy" is for

My IP route is:
default via 198.18.0.1 dev tun0 metric 20 
default via 10.13.137.1 dev eth0 proto dhcp src 10.13.137.151 metric 100 
10.13.137.0/24 dev eth0 proto kernel scope link src 10.13.137.151 metric 100 
10.13.137.1 dev eth0 proto dhcp scope link src 10.13.137.151 metric 100 

I ran ip route add 10.13.137.1 dev eth0 metric 10

but still get 
curl: (56) Recv failure: Connection reset by peer


My new IP route is:
default via 198.18.0.1 dev tun0 metric 20 
default via 10.13.137.1 dev eth0 proto dhcp src 10.13.137.151 metric 100 
10.13.137.0/24 dev eth0 proto kernel scope link src 10.13.137.151 metric 100 
10.13.137.1 dev eth0 scope link metric 10 
10.13.137.1 dev eth0 proto dhcp scope link src 10.13.137.151 metric 100 

I'm sorry I'm a bit slow)

But what am I doing wrong?

My goal is to force the whole system though the socks5 remote proxy server (as if it was wireguard VPN)  If its possible at all

@heiher

**Comment by heiher** [comment]
@hosseinkhojany Try to run xray on other hosts in the LAN to rule out the presence of unknown upstream servers that are not included in high-priority routing rules.

**Comment by heiher** [comment]
@MikeAlinov The upstream server is a remote proxy service, such as the upstream connected by xray.

**Comment by MikeAlinov** [comment]
@hosseinkhojany 

Should I install the xray?

I want to connect my whole system to connect to a remote socks5 proxy server as if it was  aVPN

So far I was doing these steps to achieve this (with no luck):

sudo apt update
sudo apt install build-essential

apt install resolvconf



git clone --recursive https://github.com/heiher/hev-socks5-tunnel
cd hev-socks5-tunnel
make


sudo nano /usr/local/bin/proxyty.yml

tunnel:
  # Interface name
  name: tun0
  # Interface MTU
  mtu: 8500
  # Multi-queue
  multi-queue: true
  # IPv4 address
  ipv4: 198.18.0.1
  # IPv6 address
  ipv6: fc00::1

socks5:
  # Socks5 server port
  port: 14600
  # Socks5 server address (ipv4/ipv6)
  address: 202.182.69.181
  # Socks5 UDP relay mode (tcp|udp)
  udp: 'udp'
  # Socks5 server username
  username: 'xxxxxxxxx'
  # Socks5 server password
  password: 'xxxxxxxxxx'

#misc:
   # task stack size (bytes)
#  task-stack-size: 20480
   # connect timeout (ms)
#  connect-timeout: 5000
   # read-write timeout (ms)
#  read-write-timeout: 60000
   # stdout, stderr or file-path
#  log-file: stderr
   # debug, info, warn or error
#  log-level: warn
   # If present, run as a daemon with this pid file
#  pid-file: /run/hev-socks5-tunnel.pid
   # If present, set rlimit nofile; else use default value
#  limit-nofile: 65535


sudo nano /etc/systemd/system/proxyty.service


[Unit]
Description=proxyty service
After=network.target

[Service]
ExecStart=/root/hev-socks5-tunnel/bin/hev-socks5-tunnel /usr/local/bin/proxyty.yml
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target





systemctl daemon-reload


sudo systemctl enable proxyty.service


sudo systemctl start proxyty.service


sudo systemctl status proxyty.service



sudo ip route add default dev tun0 metric 20




Could you please tell me, what am I doing wrong? What stems should I add? Why? And how?

I'm sorry for being for being a pain in the a**

**Comment by MikeAlinov** [comment]
@hosseinkhojany  But that's the thing, I don't even have x-ray installed.
Should I install it?

What steps should I add to make it finally work?

**Comment by hosseinkhojany** [comment]
I finally succeeded with this shell:
parameter 1: is your socks5 host domain or ip 
parameter 2: current directory or directory which place hev_tun
parameter 3: xray config you can remote it

`#!/bin/bash

#variables
host_name=$1 # It should be a domin in my case
xray_ip=$(dig +short $host_name) 
def_gate=$(ip r | grep 'default' | awk '{print$3}') # This will output your default gateway ip address . if command fails try finding the deault gateway ip by using 'ip r' command

ip tuntap del dev tun0 mode tun user $USER
ip route del $xray_ip via $def_gate

ip tuntap add dev tun0 mode tun user $USER
ip addr add 10.0.0.1/24 dev tun0
ip addr add fdfe:dcba:9876::1/125 dev tun0
ip route add $xray_ip via $def_gate
ip link set tun0 up
ip -6 link set tun0 up
ip route add default dev tun0
ip -6 route add default dev tun0

chmod +x hev_tun
chmod +x xray

$2/xray -c $3 > /dev/null &
# sleep 2

# insert/update hosts entry
ip_address=$xray_ip
# find existing instances in the host file and save the line numbers
suffix="XrayTun.linux"
matches_in_hosts="$(grep -n "$suffix" /etc/hosts | cut -f1 -d:)"

host_entry="${ip_address} ${host_name} ${suffix}"

echo "Please enter your password if requested."

if [ ! -z "$matches_in_hosts" ]
then
    echo "Updating existing hosts entry."
    # iterate over the line numbers on which matches were found
    while read -r line_number; do
        # replace the text of each line with the desired host entry
        sudo sed -i "${line_number}s/.*/${host_entry} /" /etc/hosts
    done <<< "$matches_in_hosts"
else
    echo "Adding new hosts entry."
    echo "$host_entry" | sudo tee -a /etc/hosts > /dev/null
fi

$2/hev_tun config.yml‍‍`

**Comment by MikeAlinov** [comment]
@heiher

Should I install the xray?

I want to connect my whole system to connect to a remote socks5 proxy server as if it was aVPN

So far I was doing these steps to achieve this (with no luck):

sudo apt update
sudo apt install build-essential

apt install resolvconf

git clone --recursive https://github.com/heiher/hev-socks5-tunnel
cd hev-socks5-tunnel
make

sudo nano /usr/local/bin/proxyty.yml

tunnel:
name: tun0
mtu: 8500
multi-queue: true
ipv4: 198.18.0.1
ipv6: fc00::1

socks5:
port: 14600
address: 202.182.69.181
udp: 'udp'
username: 'xxxxxxxxx'
password: 'xxxxxxxxxx'

sudo nano /etc/systemd/system/proxyty.service

[Unit]
Description=proxyty service
After=network.target

[Service]
ExecStart=/root/hev-socks5-tunnel/bin/hev-socks5-tunnel /usr/local/bin/proxyty.yml
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target

systemctl daemon-reload

sudo systemctl enable proxyty.service

sudo systemctl start proxyty.service

sudo systemctl status proxyty.service

sudo ip route add default dev tun0 metric 20

Could you please tell me, what am I doing wrong? What stems should I add? Why? And how?

I'm sorry for being for being a pain in the a**

**Comment by MikeAlinov** [comment]
@heiher

Should I install the xray (because I don,t have it)?

I want to connect my whole system to connect to a remote socks5 proxy server as if it was aVPN

So far I was doing these steps to achieve this (with no luck):

sudo apt update
sudo apt install build-essential

apt install resolvconf

git clone --recursive https://github.com/heiher/hev-socks5-tunnel
cd hev-socks5-tunnel
make

sudo nano /usr/local/bin/proxyty.yml

tunnel:
name: tun0
mtu: 8500
multi-queue: true
ipv4: 198.18.0.1
ipv6: fc00::1

socks5:
port: 14600
address: 202.182.69.181
udp: 'udp'
username: 'xxxxxxxxx'
password: 'xxxxxxxxxx'

sudo nano /etc/systemd/system/proxyty.service

[Unit]
Description=proxyty service
After=network.target

[Service]
ExecStart=/root/hev-socks5-tunnel/bin/hev-socks5-tunnel /usr/local/bin/proxyty.yml
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target

systemctl daemon-reload

sudo systemctl enable proxyty.service

sudo systemctl start proxyty.service

sudo systemctl status proxyty.service

sudo ip route add default dev tun0 metric 20

Could you please tell me, what am I doing wrong? What stems should I add? Why? And how?

I'm sorry for being for being a pain in the a**

**Comment by hosseinkhojany** [comment]
@MikeAlinov 
yes you can also use xray socks protocol 
https://xtls.github.io/en/config/outbounds/socks.html
and send it stream to hev tunnel

**Comment by MikeAlinov** [comment]
@heiher 

I ran:
ip route add 202.182.69.181 dev eth0 metric 10
ip route add default dev tun0 metric 20

And I still get the 
curl: (56) Recv failure: Connection reset by peer
when running "curl ifconfig.me"

IP route:
default dev tun0 scope link metric 20 
default via 10.13.137.1 dev eth0 proto dhcp src 10.13.137.151 metric 100 
10.13.137.0/24 dev eth0 proto kernel scope link src 10.13.137.151 metric 100 
10.13.137.1 dev eth0 proto dhcp scope link src 10.13.137.151 metric 100 
202.182.69.181 dev eth0 scope link metric 10 

sudo systemctl status proxyty.service
● proxyty.service - proxyty service
     Loaded: loaded (/etc/systemd/system/proxyty.service; enabled; vendor preset: enabled)
     Active: active (running) since Tue 2023-08-01 18:42:48 UTC; 20min ago
   Main PID: 179 (hev-socks5-tunn)
      Tasks: 1 (limit: 1101)
     Memory: 1.6M
        CPU: 7ms
     CGroup: /system.slice/proxyty.service
             └─179 /root/hev-socks5-tunnel/bin/hev-socks5-tunnel /usr/local/bin/proxyty.yml

Aug 01 18:42:48 kozak systemd[1]: Started proxyty service.
Aug 01 18:47:00 kozak hev-socks5-tunnel[179]: [2023-08-01 18:47:00] [E] 0x5588cbc7ae40 socks5 client connect
Aug 01 18:47:00 kozak hev-socks5-tunnel[179]: [2023-08-01 18:47:00] [E] 0x5588cbc7ae40 socks5 client connect
Aug 01 18:47:00 kozak hev-socks5-tunnel[179]: [2023-08-01 18:47:00] [E] 0x5588cbc7ae40 socks5 session connect

the service is running, the tunnel is up

**Comment by MikeAlinov** [comment]
@heiher 

I ran:
ip route add 202.182.69.181 dev eth0 metric 10
ip route add default dev tun0 metric 20

And I still get the 
curl: (56) Recv failure: Connection reset by peer
when running "curl ifconfig.me"

IP route:
default dev tun0 scope link metric 20 
default via 10.13.137.1 dev eth0 proto dhcp src 10.13.137.151 metric 100 
10.13.137.0/24 dev eth0 proto kernel scope link src 10.13.137.151 metric 100 
10.13.137.1 dev eth0 proto dhcp scope link src 10.13.137.151 metric 100 
202.182.69.181 dev eth0 scope link metric 10 

sudo systemctl status proxyty.service
● proxyty.service - proxyty service
     Loaded: loaded (/etc/systemd/system/proxyty.service; enabled; vendor preset: enabled)
     Active: active (running) since Tue 2023-08-01 18:42:48 UTC; 20min ago
   Main PID: 179 (hev-socks5-tunn)
      Tasks: 1 (limit: 1101)
     Memory: 1.6M
        CPU: 7ms
     CGroup: /system.slice/proxyty.service
             └─179 /root/hev-socks5-tunnel/bin/hev-socks5-tunnel /usr/local/bin/proxyty.yml

Aug 01 18:42:48 kozak systemd[1]: Started proxyty service.
Aug 01 18:47:00 kozak hev-socks5-tunnel[179]: [2023-08-01 18:47:00] [E] 0x5588cbc7ae40 socks5 client connect
Aug 01 18:47:00 kozak hev-socks5-tunnel[179]: [2023-08-01 18:47:00] [E] 0x5588cbc7ae40 socks5 client connect
Aug 01 18:47:00 kozak hev-socks5-tunnel[179]: [2023-08-01 18:47:00] [E] 0x5588cbc7ae40 socks5 session connect

ip link show tun0
2: tun0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 8500 qdisc mq state UNKNOWN mode DEFAULT group default qlen 500
    link/none 

the service is running, the tunnel is up

**Comment by MikeAlinov** [comment]
@heiher

I ran:
ip route add 202.182.69.181 dev eth0 metric 10
ip route add default dev tun0 metric 20

And I still get the
curl: (56) Recv failure: Connection reset by peer
when running "curl ifconfig.me"

IP route:
default dev tun0 scope link metric 20
default via 10.13.137.1 dev eth0 proto dhcp src 10.13.137.151 metric 100
10.13.137.0/24 dev eth0 proto kernel scope link src 10.13.137.151 metric 100
10.13.137.1 dev eth0 proto dhcp scope link src 10.13.137.151 metric 100
202.182.69.181 dev eth0 scope link metric 10

sudo systemctl status proxyty.service
● proxyty.service - proxyty service
Loaded: loaded (/etc/systemd/system/proxyty.service; enabled; vendor preset: enabled)
Active: active (running) since Tue 2023-08-01 18:42:48 UTC; 20min ago
Main PID: 179 (hev-socks5-tunn)
Tasks: 1 (limit: 1101)
Memory: 1.6M
CPU: 7ms
CGroup: /system.slice/proxyty.service
└─179 /root/hev-socks5-tunnel/bin/hev-socks5-tunnel /usr/local/bin/proxyty.yml

Aug 01 18:42:48 kozak systemd[1]: Started proxyty service.
Aug 01 18:47:00 kozak hev-socks5-tunnel[179]: [2023-08-01 18:47:00] [E] 0x5588cbc7ae40 socks5 client connect
Aug 01 18:47:00 kozak hev-socks5-tunnel[179]: [2023-08-01 18:47:00] [E] 0x5588cbc7ae40 socks5 client connect
Aug 01 18:47:00 kozak hev-socks5-tunnel[179]: [2023-08-01 18:47:00] [E] 0x5588cbc7ae40 socks5 session connect

ip link show tun0
2: tun0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 8500 qdisc mq state UNKNOWN mode DEFAULT group default qlen 500
link/none

the service is running, the tunnel is up

Can you please start Ubuntu 22.04 container and check whats what

I'll give you the credentials to my socks5 service that I purchased

port: 14600
address: 202.182.69.181
username: 'mihallostar'
password: '6993f66d44'

**Comment by MikeAlinov** [comment]
@heiher 

I am using a digital ocean droplet and run lxd container inside of it.

**Comment by MikeAlinov** [comment]
@heiher

**Comment by MikeAlinov** [comment]
@heiher 

Please help me out here.

I also connected to the Poxy on my Android using the same internet connection as my desktop and using ProxyDroid application, it connected just fine.

**Comment by MikeAlinov** [comment]
@heiher Have you tried running it inside of Ubuntu 22.04 lxd container?

**Comment by heiher** [comment]
resolved?

**Comment by MikeAlinov** [comment]
@heiher 

No.

Have you tried replicating it a Ubuntu 22.04 container?

Please let me know, cos I need to know if it is me doing something wrong or not.

**Comment by heiher** [comment]
@MikeAlinov Hmm. Could you provide an environment (like a VPS) where I deploy an example. (Email to me)

**Comment by MikeAlinov** [comment]
@heiher Can't send anything to ckBoZXYuY2M= email address I have found on your site

What address should I send the SSH IP and password to the digital ocean droplet,  as well as proxy credentials?

**Comment by MikeAlinov** [comment]
Can you give me some other email?

**Comment by hosseinkhojany** [comment]
it possible to start xray and hev-socks-tun without by pass upstream ?
@heiher

**Comment by MikeAlinov** [comment]
@heiher Please, give me your email.

**Comment by heiher** [comment]
> @heiher Can't send anything to ckBoZXYuY2M= email address I have found on your site
> 
> What address should I send the SSH IP and password to the digital ocean droplet, as well as proxy credentials?

ckBoZXYuY2M= Why? I can receive email from other.
