### ISSUE TITLE
error: expected identifier or '('

### ISSUE THREAD

**Issue by EmpireOneDevs** [heiher/hev-socks5-tunnel#5]
Hi, i've linked this library to my project, just adding this to gradle:

`externalNativeBuild {
        ndkBuild {
            path file('../../../hev-socks5-tunnel-master/jni/Android.mk')
        }
    }`

Now when building it it throws the below error, could you please help me out with it ? 

`In file included from C:\Users\User\Downloads\hev-socks5-tunnel-master\jni\src\hev-socks5-session.c:14:
C:\Users\User\Downloads\hev-socks5-tunnel-master\jni\third-part\hev-task-system\include\hev-task.h:1:1: error: expected identifier or '('`

![image](https://user-images.githubusercontent.com/40423351/105571870-17a51000-5d5c-11eb-973f-4753ccf946df.png)

Any Help would be kindly appreciated, 
Thanks

**Comment by heiher** [comment]
Because the Windows file system does not support symbolic links, you need to replace the files with the same name in the `include` directory with the files in the `src` directory:

e.g.
```bash
cp src/kern/task/hev-task.h include/hev-task.h
...
```

**Comment by EmpireOneDevs** [comment]
Much appreciated, but how do i do that with android studio ? or i have to define manually each file location ?
Thanks

**Comment by heiher** [comment]
If you can't start building after replacement, I think you can fork this project and modify it, and then integrate it into your project. :)

**Comment by EmpireOneDevs** [comment]
I think im not getting it, Android Studio generates the include folder & i
cannot modify it as i see, probably i'd have to modify the paths &
re-import...
Thanks

**Comment by EmpireOneDevs** [comment]
Off topic sorry, where should i put the config file in the android studio project ?
Thanks

> 
> 
> If you can't start building after replacement, I think you can fork this project and modify it, and then integrate it into your project. :)

**Comment by EmpireOneDevs** [comment]
Fixed the paths, no errors thrown , can't get it work though...Don't know where to include the file & how to debug the reason...

**Comment by heiher** [comment]
> Fixed the paths, no errors thrown , can't get it work though...Don't know where to include the file & how to debug the reason...

Please verify the establishment of TCP connection via IPv4/IPv6 address first, and then look at DNS.

**Comment by EmpireOneDevs** [comment]
> 
> 
> > Fixed the paths, no errors thrown , can't get it work though...Don't know where to include the file & how to debug the reason...
> 
> Please verify the establishment of TCP connection via IPv4/IPv6 address first, and then look at DNS.

Does it have a default configuration ? ( The 1080 port is also closed )
I can ping the device & it uses the public DNS ,the only open port is ICMP,  i wonder where exactly should i put the `main.yml` config file ? 

![image](https://user-images.githubusercontent.com/40423351/105667636-52d24b00-5ee4-11eb-890b-9bcf06b6be9b.png)

**Comment by heiher** [comment]
What do you need to do? capture packets via VPN? (I see you integrate hev-socks5-server in the project.

**Comment by EmpireOneDevs** [comment]
> 
> 
> What do you need to do? capture packets via VPN? (I see you integrate hev-socks5-server in the project.

No not capturing packets , it's an app where the android device comes as proxy server for other clients.

**Comment by heiher** [comment]
Looks this is easy to do, only hev-socks5-server is dependent. If it runs as a standalone process, it's same as running on Linux. If it run as an Android service, something are missing, such as:
* JNI
* Service manager
* Config file

You can refer to:
* https://github.com/heiher/hev-socks5-tproxy/blob/master/src/hev-jni.c
* https://github.com/heiher/hev-htproxy/blob/master/app/src/main/java/hev/htproxy/TProxyService.java#L133-L165
* https://github.com/heiher/hev-socks5-server/blob/master/conf/main.yml
