### ISSUE TITLE
编译问题，提示缺少文件

### ISSUE THREAD

**Issue by llxlpej** [heiher/hev-socks5-tunnel#51]
按照readme中的方法使用android ndk编译，ndk-build（版本是21.4.7075529）后报错提示lwip/tcp.h找不到
![image](https://github.com/heiher/hev-socks5-tunnel/assets/38293372/ceda31bd-f8e8-49b3-bb5d-9b7793e3191b)
麻烦问下这个怎么处理啊

**Comment by heiher** [comment]
项目中包含符号链接，Windows的文件系统不支持，手工替换一下吧。
