### ISSUE TITLE
It possible to use hev-sock5-tunnel in macos developer id ?

### ISSUE THREAD

**Issue by hosseinkhojany** [heiher/hev-socks5-tunnel#52]
because when I using hev-sock5 in developer id it print this error and macos packet tunnel not starting 

NESMVPNSession[Primary Tunnel:zVPN Xray :(null)]: failed to set the MTU to 9000

**Comment by heiher** [comment]
Emm. Is it a macos limitation?

**Comment by hosseinkhojany** [comment]
<img width="1280" alt="Screenshot 2023-08-16 at 11 09 08 AM" src="https://github.com/heiher/hev-socks5-tunnel/assets/37432839/0dcddc90-7fea-41e4-a246-c3d6b1fe51bf">
I set MTU 1500 but still I received this error
