### ISSUE TITLE
支持tcp+tls吗？

### ISSUE THREAD

**Issue by China-Zhao** [heiher/hev-socks5-tunnel#53]

**Comment by heiher** [comment]
没直接支持，建议套其它传输层封装使用。

**Comment by China-Zhao** [comment]
> 没直接支持，建议套其它传输层封装使用。

是不是sock5协议封装的有问题，通过wireshark抓包并不能识别sock5协议

**Comment by China-Zhao** [comment]
> 

`tunnel:
  mtu: 1500

socks5:
  port: 8083
  address: 127.0.0.1
  udp: 'tcp'

misc:
  task-stack-size: 20480
  connect-timeout: 5000
  read-write-timeout: 60000
  log-file: stderr
  log-level: debug
  limit-nofile: 65535
`
address配置127.0.0.1这样连接不上本地的服务，如果是其他地址，是能连上的，是哪里的配置不对吗？

**Comment by China-Zhao** [comment]
ios通过虚拟网卡拦截数据包，能够拦截到虚拟网卡的包，但是没有正常转发到本地的服务，通过配置PacketTunnelProvider拓展中的NEProxySettings是能够正常转发的， 可以帮忙看看是哪里的问题导致的吗
        let proxy = NEProxySettings()
        proxy.httpEnabled = true
        proxy.httpServer = NEProxyServer(address: "127.0.0.1", port: 8036)
        proxy.httpsEnabled = true
        proxy.httpsServer = NEProxyServer(address: "127.0.0.1", port: 8036)
配置是上面的；下面是库的日志：

<img width="639" alt="image" src="https://github.com/heiher/hev-socks5-tunnel/assets/10826537/531ae69a-b063-4235-a15d-0958b3b429b4">

**Comment by heiher** [comment]
从错误看是连接socks5服务器端出错了，原因不清楚了。
