### ISSUE TITLE
udp forward

### ISSUE THREAD

**Issue by hwk888** [heiher/hev-socks5-tunnel#58]
During use, UDP will not be able to receive packets from the network card, and it will wait for data, but it is normal to use it on other platforms, and I don't know what will cause it.

The UDP log output stops here, the previous UDP protocol handshake is normal, and the UDP data does not receive any data by the forwarding time。
 
LOG_D ("%p socks5 udp recvfrom udp", self);

    adat = HEV_SOCKS5 (self)->data;
    alen = sizeof (struct sockaddr_in6);
    rlen = hev_task_io_socket_recvfrom (hev_socks5_udp_get_fd (self), rbuf,
                                        sizeof (rbuf), 0, adat, &alen,
                                        task_io_yielder, self);

**Comment by heiher** [comment]
I need more information about how to reproduce it? and which platforms works and which not?

**Comment by hwk888** [comment]
I tested on the armv7l platform, same platform, different router

**Comment by heiher** [comment]
Any more? No ideas for current info.

**Comment by hwk888** [comment]
There is a problem with the ASUS AC1900c test, and the ASUS ax56u test is normal. The problematic test found that UDP was not successful

**Comment by hwk888** [comment]
[2023-09-16 14:27:18] [D] 0x4014ebe8 socks5 session udp splice
[2023-09-16 14:27:18] [D] 0x4014ebe8 socks5 udp sendto
[2023-09-16 14:27:18] [D] 0x4014ebe8 socks5 udp write udp
[2023-09-16 14:27:18] [D] 0x4014ebe8 socks5 session udp fwd f send
[2023-09-16 14:27:18] [D] 0x4014ebe8 socks5 udp recvfrom udp
log~

**Comment by hwk888** [comment]
Does Linux kernel version 2.6.36.4brcmarm support? I run the program under the kernel, and UDP cannot be sent to the protocol stack，I found UDP to be problematic under this kernel and does not send and receive data properly

**Comment by hwk888** [comment]
Excuse me, and I want to ask. How to start the lwip api/socket.c log, I tried several switches but could not start the module log

**Comment by heiher** [comment]
> Does Linux kernel version 2.6.36.4brcmarm support? I run the program under the kernel, and UDP cannot be sent to the protocol stack，I found UDP to be problematic under this kernel and does not send and receive data properly

I'm not sure.

**Comment by heiher** [comment]
I suggest that you try using hev-socks5-tunnel with hev-socks5-server in UDP relay over TCP mode.

**Comment by hwk888** [comment]
I have tried this method, and the result is the same. udp can't send and receive normally.

**Comment by hwk888** [comment]
I'm running in the router system.

**Comment by heiher** [comment]
Could you paste the full logs of hev-socks5-tunnel and hev-socks5-server?

log config:
```yaml
misc:
  log-file: stderr
  log-level: debug
```

**Comment by hwk888** [comment]
OK
