### ISSUE TITLE
fatal error: lwip/init.h: No such file or directory 15 | #include "lwip/init.h"

### ISSUE THREAD

**Issue by firephx** [heiher/hev-socks5-tunnel#6]
fatal error: lwip/init.h: No such file or directory
15 | #include "lwip/init.h"
|          ^~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:103: build/hev-main.o] Error 1

I'am using Arch linux and i can't build it
please help!

**Comment by heiher** [comment]
I guess you don't clone sub-modules, retry:

```bash
git clone --recursive https://github.com/heiher/hev-socks5-tunnel
```
