### ISSUE TITLE
合并.a的时候出现警告

### ISSUE THREAD

**Issue by Timssse** [heiher/hev-socks5-tunnel#71]
siru-mac8@TG hev-socks5-tunnel % libtool -static -o libhev-socks5-tunnel.a \
                   bin/libhev-socks5-tunnel1.a \
                   third-part/lwip/bin/liblwip.a \
                   third-part/yaml/bin/libyaml.a \
                   third-part/hev-task-system/bin/libhev-task-system.a
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: warning renaming duplicate member name 'hev-list.o' from 'third-part/hev-task-system/bin/libhev-task-system.a(hev-list.o)' and 'bin/libhev-socks5-tunnel1.a(hev-list.o)'
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: warning renaming duplicate member name 'hev-rbtree.o' from 'bin/libhev-socks5-tunnel1.a(hev-rbtree.o)' and 'third-part/hev-task-system/bin/libhev-task-system.a(hev-rbtree.o)'
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: warning renaming duplicate member name 'mem.o' from 'third-part/lwip/bin/liblwip.a(mem.o)' and 'third-part/lwip/bin/liblwip.a(mem.o)'

**Comment by heiher** [comment]
多个静态库合并是有重复的符号，不过不影响，因为功能是相同的。

**Comment by Timssse** [comment]
好的

**Comment by Timssse** [comment]
大佬，我想咨询一个问题，目前我参考的https://github.com/arror/Mango 实现，但是在iOS14上会断开连接

**Comment by Timssse** [comment]
同时本地配置必须是::1才可以，127.0.0.1就不行

**Comment by heiher** [comment]
这个情况我也不太清楚，我没有iOS的环境。
