### ISSUE TITLE
docker方式启动后 容器和宿主机之间就互相没发联通了

### ISSUE THREAD

**Issue by skier789** [heiher/hev-socks5-tunnel#72]
谢谢大佬出了dockerfile 很好用 但是有个小问题
比如在容器里无法请求172.17.0.1
宿主机里也无法请求 172.17.0.2了

**Comment by heiher** [comment]
好的，我再加个配置项让指定的地址段（默认值172.17.0.0/24）走默认路由。

**Comment by heiher** [comment]
修复： https://github.com/heiher/hev-socks5-tunnel/commit/11d1b2ba88e40709f35ac0695bdec764f55936a3

**Comment by skier789** [comment]
感谢大佬!
