### ISSUE TITLE
I can't ndk-build the program, my ndk version is android-ndk-r26b,what's the problem?

### ISSUE THREAD

**Issue by potato1899** [heiher/hev-socks5-tunnel#75]
[armeabi-v7a] Compile thumb  : hev-socks5-tunnel <= hev-object.c
[armeabi-v7a] Compile thumb  : hev-socks5-tunnel <= hev-rbtree.c
[armeabi-v7a] Compile thumb  : hev-socks5-tunnel <= hev-socks5-authenticator.c
[armeabi-v7a] Compile thumb  : hev-socks5-tunnel <= hev-socks5-client-tcp.c
In file included from jni/src/core/src/hev-socks5-client-tcp.c:12:
jni/third-part/hev-task-system/include/hev-memory-allocator.h:1:1: error: expected identifier or '('
../src/mem/api/hev-memory-allocator-api.h
^
In file included from jni/src/core/src/hev-socks5-client-tcp.c:14:
In file included from jni/src/core/src/hev-socks5-misc-priv.h:15:
jni/third-part/hev-task-system/include/hev-task.h:1:1: error: expected identifier or '('
../src/kern/task/hev-task.h

**Comment by heiher** [comment]
build on Windows?

**Comment by potato1899** [comment]
> build on Windows?

Yes，

**Comment by heiher** [comment]
Um. There are symlink files in the project and submodules that cannot be created on Windows.
