### ISSUE TITLE
Tun2SocksKit for iOS no longer exist

### ISSUE THREAD

**Issue by houmie** [heiher/hev-socks5-tunnel#79]
Hello

https://github.com/heiher/hev-socks5-tunnel#ios that is linked at the bottom of the page no longer exists.

The repo https://github.com/daemooon/Tun2SocksKit is deleted or set by mistake to Private.

This was working until yesterday.  What do we do now?

**Comment by heiher** [comment]
Uh, I don't know what happened. Let's ask the author @arror

**Comment by heiher** [comment]
There is a fork: https://github.com/dumpmemory/Tun2SocksKit

**Comment by houmie** [comment]
Thank you for your response.  Unfortunately I tried that fork already and it doesn't work, because it refers back to the repo of arror.  Do you see that from the screenshot? I wonder if this is something that can be fixed in the SPM file.

<img width="1027" alt="Screenshot 2023-11-18 at 07 16 56" src="https://github.com/heiher/hev-socks5-tunnel/assets/1832933/1113060c-add1-4e0b-818f-943ef5e075e6">

I emailed arror last night, but no response.

**Comment by heiher** [comment]
https://github.com/jzau/tun2sockskit

**Comment by houmie** [comment]
Thanks @heiher 

I just tried it again with this URL https://github.com/jzau/tun2sockskit and I reseted the cache too.

<img width="1111" alt="Screenshot 2023-11-18 at 14 55 57" src="https://github.com/heiher/hev-socks5-tunnel/assets/1832933/0592b293-5410-4309-bcf2-5234db02e77d">

Do you see it's downloading version 2.5.5 from the new jzau repo. However for some reason it is still refering to the old arcor path.  Bizarre.

```https://github.com/arror/Tun2SocksKit/releases/download/2.5.5/HevSocks5Tunnel.xcframework.zip```

I don't think it's a caching problem on my side. I cleansed everything and even tried it on a complete new project. It's not working, I'm afraid.

**Comment by EbrahimTahernejad** [comment]
https://github.com/EbrahimTahernejad/Tun2SocksKit

**Comment by houmie** [comment]
After the latest update, it is now working. However only on the master branch. Not 2.5.5 release.  

Thank you for chasing this and making it happen @heiher.

The only outstanding issue is that it doesn't include support for the simulator. The old version 2.5.3 that is no longer available  had support for it. Right now it's not possible to open the app in the simulator. I raised an issue there, let see if it gets picked up.  Thanks

**Comment by houmie** [comment]
> https://github.com/EbrahimTahernejad/Tun2SocksKit

Hi Ebrahim, yes, I found your repo as well. It looks very good.  But there is a concern I have as you have changed it without updating the README file.

It used to be: 
```
Socks5Tunnel.run(withConfig: configurationFilePath), privacy: .public)
```

But your repo requires the FileDescriptor to be passed in. It is no longer automatic:

```
Socks5Tunnel.run(withConfig: configurationFilePath, using: 4) { status in }
```

Your repo didn't work on my iPad, but worked on iPhone.  Maybe 4 is the wrong value to pass in.  It would be good if you could enable the ```issues``` section on your Github repo, so users can raise bugs and discuss them with you.

Thanks,
Houman

**Comment by EbrahimTahernejad** [comment]
@houmie try version 3.1.5

**Comment by houmie** [comment]
@EbrahimTahernejad It works great now! Thank you.   It works both on iPad and iOS simulator.  Do I need to add `Tun2SocksKitC` too? Or is adding `Tun2SocksKit` enough?  Or do I need to add both?

Brilliant project. Thanks

**Comment by EbrahimTahernejad** [comment]
You only need to import Tun2SocksKit
