### ISSUE TITLE
how to set username/password?

### ISSUE THREAD

**Issue by mokhtarabadi** [heiher/hev-socks5-tunnel#8]

**Comment by heiher** [comment]
The socks5 client does not support authentication . Socks5 transmission is plain data, It's recommended to use locally.

**Comment by mokhtarabadi** [comment]
so what is this? https://github.com/heiher/hev-socks5-server/blob/a517ee48725cad8eb133b33287c2ad875fbebebf/conf/main.yml#L11
if I set username/password in hev-socks5-server, client means this repo (hev-socks5-tunnel) didn't work?

and yes I use tls + http2 to stream data as something like you implement in android (hev-htproxy).

**Comment by heiher** [comment]
> so what is this? https://github.com/heiher/hev-socks5-server/blob/a517ee48725cad8eb133b33287c2ad875fbebebf/conf/main.yml#L11
> if I set username/password in hev-socks5-server, client means this repo (hev-socks5-tunnel) didn't work?

Yes. Only the socks5 server supports authentication. :smiley: 

> 
> and yes I use tls + http2 to stream data as something like you implement in android (hev-htproxy).

You'd better implement encryption and authentication at the transport layer.

**Comment by mokhtarabadi** [comment]
if possible implement username/password authentication for clients too, I think that will be useful...

using something like https://github.com/erebe/wstunnel is a good idea?

**Comment by heiher** [comment]
Could you please verify https://github.com/heiher/hev-socks5-tunnel/commit/935a4006524134aed5e3a4d292f3c3c2a6ff753d ?

Thanks
