### ISSUE TITLE
请问安卓和 iOS 的实现逻辑是什么？

### ISSUE THREAD

**Issue by Cyberbolt** [heiher/hev-socks5-tunnel#89]
通过一定的方法调用系统 VPN 接口，然后使用 hev-socks5-tunnel 将流量转发到 socks 5 Server，socks 5 Server 再转为 v2ray 等协议和远程代理服务器交互。这个 socks 5 代理服务器是运行在安卓和 iOS 本地的吗？监听的本地端口吗

**Comment by heiher** [comment]
本项目只是将Tunnel上的TCP和UDP流量转换为Socks5协议接入上行的Socks5服务器。Socks5服务器端再向上的互联结构不作规定，可以有自己的传输封装、分流规则等等。Socks5服务器端可以运行在本地，也可以在远程，视业务需要而定吧。
