### ISSUE TITLE
can't make so files in android studio

### ISSUE THREAD

**Issue by itsDantes** [heiher/hev-socks5-tunnel#94]
i can't make so files for this lib and use it in my android projects.

i test 2 way .  first i cloned your [**android project - sockstun**](https://github.com/heiher/sockstun) into my android studio and getting this error

![e1](https://github.com/heiher/hev-socks5-tunnel/assets/37669470/2a8d0974-4f52-4cd9-9820-f165f837592b)
`
In file included from C:/Users/windows/StudioProjects/sockstun/app/src/main/jni/hev-socks5-tunnel/src/core/src/hev-socks5-client-tcp.c:12:
C:/Users/windows/StudioProjects/sockstun/app/src/main/jni/hev-socks5-tunnel/third-part/hev-task-system/include/hev-memory-allocator.h:1:1: error: expected identifier or '('
../src/mem/api/hev-memory-allocator-api.h
^
`
your sockstun project it outdated , i upgraded your project gradle and finaly could run your project but getting this error.

also there is another project that [use your lib](https://github.com/SaeedDev94/Xray), but this project is also use sockstun ways and using **externalNativeBuild** for making so files. is there another android project that use this lib ? bc both of that projects using same way and both is not working.

then i tried to build it via windows cmd by [**this way**](https://github.com/heiher/hev-socks5-tunnel?tab=readme-ov-file#android):
![e2](https://github.com/heiher/hev-socks5-tunnel/assets/37669470/7b9b7aa4-6038-4f7e-a2a3-d0248f2b7ff8)

my cmd was:
```
mkdir hev-socks5-tunnel
cd hev-socks5-tunnel
git clone --recursive https://github.com/heiher/hev-socks5-tunnel jni
C:\Users\windows\AppData\Local\Android\Sdk\ndk\25.1.8937393\ndk-build
```

whats the problem ? how can make **.so** files for my android project?

**Comment by heiher** [comment]
https://github.com/heiher/hev-socks5-tunnel/issues/5#issuecomment-765883956

**Comment by itsDantes** [comment]
@heiher i getting this error because running this command in windows ? so what about [sockstun(https://github.com/heiher/sockstun) project? it also not working in android studio and getting 
`
In file included from C:/Users/windows/StudioProjects/sockstun/app/src/main/jni/hev-socks5-tunnel/src/core/src/hev-socks5-client-tcp.c:12: C:/Users/windows/StudioProjects/sockstun/app/src/main/jni/hev-socks5-tunnel/third-part/hev-task-system/include/hev-memory-allocator.h:1:1: error: expected identifier or '(' ../src/mem/api/hev-memory-allocator-api.h ^
`
if both is windows so where should we run android ndk-build ? linux? should i download ndk-build for linux and make project there?

**Comment by heiher** [comment]
hev-socks5-tunnel (and submodules) contain symlink files, which are not supported on Windows file systems. So sockstun can only be compiled on Unix systems, including WSL. Only the command line SDK is required.

**Comment by itsDantes** [comment]
@heiher well, i installed linux command line and **make** command getting error


![Untitled](https://github.com/heiher/hev-socks5-tunnel/assets/37669470/a9622412-d981-4aea-8e51-f9ab9945a544)

**Comment by itsDantes** [comment]
the only way that not getting error is below folder structure

in my android **src\main** i made an **jni** folder:

![sdw](https://github.com/heiher/hev-socks5-tunnel/assets/37669470/223cac77-b48a-4b2f-b0c1-c8a993fdf218)
 
so my folder structure is like **`jni\hev-socks5-tunnel\jni`**. by this way when i run make my project in androidStudio [**like this command - externalNativeBuild**](https://github.com/heiher/sockstun/blob/8aa1d1ef85e1395f553e0251770e1adb0625cbf1/app/build.gradle#L50) everyhing works fine and i getting no error, but there is no **`.so`** files in my android project. you can see output of made projects

![make](https://github.com/heiher/hev-socks5-tunnel/assets/37669470/4632f450-5f21-4deb-8de2-666f11a73eb5)

is this folder structure is wrong ? why i cant made this lib in my project?

====================

but when i use **src\main\jni\hev-socks5-tunnel** folder structure i getting error as below
![Untitled](https://github.com/heiher/hev-socks5-tunnel/assets/37669470/1926ef12-dbf3-489e-8d26-80eaa7610e58)

```
In file included from C:/Users/windows/Desktop/project/app/src/main/jni/hev-socks5-tunnel/src/core/src/hev-socks5-client-tcp.c:12:
C:/Users/windows/Desktop/project/app/src/main/jni/hev-socks5-tunnel/third-part/hev-task-system/include/hev-memory-allocator.h:1:1: error: expected identifier or '('
../src/mem/api/hev-memory-allocator-api.h
^
In file included from C:/Users/windows/Desktop/project/app/src/main/jni/hev-socks5-tunnel/src/core/src/hev-socks5-client-tcp.c:12:
C:/Users/windows/Desktop/project/app/src/main/jni/hev-socks5-tunnel/third-part/hev-task-system/include/hev-memory-allocator.h:1:1: error: expected identifier or '('
../src/mem/api/hev-memory-allocator-api.h
^
```

doese [**externalNativeBuild command**](https://github.com/heiher/sockstun/blob/8aa1d1ef85e1395f553e0251770e1adb0625cbf1/app/build.gradle#L50) should not build projects automatically and ignore windows  symlink files ?

**Comment by itsDantes** [comment]
finally i replaced all of c header files as below format and errors fixed.
 
![ff](https://github.com/heiher/hev-socks5-tunnel/assets/37669470/198f16a2-9f0d-4a89-b44a-03d3e513c889)
